import { createVerifiedPointDatasetAdapter } from "./verifiedPointDataset";

/** Fixed source-coordinate station snapshots. Capacity and active flags retain snapshot meaning only. */
export const bikeStationsFixedPointAdapter = createVerifiedPointDatasetAdapter({
  datasetId: "tw-bike-stations-fixed-20260301", label: "公共自行車站點固定快照",
  description: "TDX 全臺公共自行車站點 9,408 筆固定 Point 快照。BikesCapacity 是站體容量，不是目前可借車數、可還空位、服務啟用狀態或即時營運資訊。",
  sourceUrl: "/geo/bike_stations.geojson",
  expectedSha256: "dbbd70b3912b8739c98c75d14a41bd0aa668bbca82f16d3012c20c48fff34b24",
  expectedSourceRows: 9408, expectedSelectedRows: 9408, fullSource: true, selection: {}, layerRefs: ["bikeStations"],
  fields: [
    { name: "record_id", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "StationUID", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "StationID", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "StationName", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "StationNameEn", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "StationAddress", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "BikesCapacity", type: "number", nullable: false, nullMeaning: null, unit: "bikes" },
    { name: "ServiceType", type: "number", nullable: false, nullMeaning: null, unit: null },
    { name: "ServiceTypeName", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "AuthorityID", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "City", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "CityCode", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "lat", type: "number", nullable: false, nullMeaning: null, unit: "degrees_north" },
    { name: "lng", type: "number", nullable: false, nullMeaning: null, unit: "degrees_east" },
    { name: "geometry", type: "json", nullable: false, nullMeaning: null, unit: null },
  ],
  publisher: "交通部 TDX（彙整各縣市公共自行車營運業者）",
  license: "政府資料開放授權條款第 1 版（OGDL-Taiwan-1.0）",
  precision: "TDX StationPosition 經既有 pipeline 轉為 WGS84 Point；可作站點位置查詢，不能當作站區邊界、停車範圍或行車路徑。",
  coverageDescription: "全臺 9,408 筆來源站點 Point；本地 raw 檔名為 2026-03-01，processed manifest 的 last_updated 為 2026-05-19，但沒有逐檔來源時間收據。此固定 SHA 快照不含即時 Availability，資料新鮮度與當前營運狀態 unknown。",
  sourceLineage: "TDX /v2/Bike/Station/City/{City} 站點快照 -> analytics bike_stations_raw_20260301.json -> bike_stations_all.geojson -> Mini bike_stations.geojson；processed 與 Mini 顯示檔 SHA dbbd70b3912b8739c98c75d14a41bd0aa668bbca82f16d3012c20c48fff34b24 完全相同。",
});

export const weatherStationsFixedPointAdapter = createVerifiedPointDatasetAdapter({
  datasetId: "tw-weather-stations-active-fixed-20251129", label: "氣象站固定快照（當時運作中）",
  description: "中央氣象署氣象站資訊中 838 筆當時運作中測站 Point。is_active=true 是 2025-11-29 名冊選取結果，不是目前線上、資料回傳或任一即時觀測變數。",
  sourceUrl: "/geo/weather_stations.geojson",
  expectedSha256: "08088afb391e63970fe979895b8f76cc9b7c9a427dc09a90dd38939a784e8222",
  expectedSourceRows: 838, expectedSelectedRows: 838, fullSource: true, selection: {}, layerRefs: ["weatherStations"],
  fields: [
    { name: "record_id", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "station_id", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "station_name", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "station_type", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "elevation_m", type: "number", nullable: false, nullMeaning: null, unit: "m" },
    { name: "longitude", type: "number", nullable: false, nullMeaning: null, unit: "degrees_east" },
    { name: "latitude", type: "number", nullable: false, nullMeaning: null, unit: "degrees_north" },
    { name: "city", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "address", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "start_date", type: "string", nullable: false, nullMeaning: null, unit: null },
    { name: "end_date", type: "string", nullable: true, nullMeaning: "當時運作中名冊未列撤站日期；不代表未來不會撤站。", unit: null },
    { name: "note", type: "string", nullable: true, nullMeaning: "來源未附測站備註。", unit: null },
    { name: "old_station_id", type: "string", nullable: true, nullMeaning: "來源未列舊站號。", unit: null },
    { name: "new_station_id", type: "string", nullable: true, nullMeaning: "來源未列新站號或接替站。", unit: null },
    { name: "is_active", type: "boolean", nullable: false, nullMeaning: null, unit: null },
    { name: "geometry", type: "json", nullable: false, nullMeaning: null, unit: null },
  ],
  publisher: "交通部中央氣象署（CWA）",
  license: "政府資料開放授權條款第 1 版（OGDL-Taiwan-1.0）及中央氣象署使用條款",
  precision: "中央氣象署名冊經既有 pipeline 轉為 WGS84 Point；可作測站位置查詢，不能當作觀測代表區域、等雨量線或即時觀測值。",
  coverageDescription: "2025-11-29 本地「氣象站資訊_運作中」CSV 經處理後有 838 筆有座標 Point；已撤站 351 筆留在 stations_all.geojson，未納本快照。processed manifest 的 last_updated 為 2026-07-07，但不作為資料觀測或取得時間。溫度、雨量、風等即時觀測未包含，資料新鮮度 unknown。",
  sourceLineage: "中央氣象署氣象站資訊_運作中.csv（本地 2025-11-29 快照）-> analytics stations.geojson -> Mini weather_stations.geojson；processed 與 Mini 顯示檔 SHA 08088afb391e63970fe979895b8f76cc9b7c9a427dc09a90dd38939a784e8222 完全相同。",
});
