import { boundedAccess, DEFAULT_VALUE_SEMANTICS, type DatasetDescriptor, type DatasetField, type Scalar, type SourceReceipt } from "./dataContracts";
import { loadPointDataset } from "./pointDatasetAdapter";
import { createReferencePointDatasetAdapter, type AdapterSnapshot } from "./queryAdapters";

const SOURCE_SHA256 = "a3abf5e8a19737ffd3cd226bddb24f0413c89b2979b812d2e223eb8fb2ca2aae";
const MANIFEST_SHA256 = "0cb6cf2ae37fb514c4f2f01200a240277d301296a17668ba4e940da0ac3dcd6c";
const SOURCE_REFERENCE = `/research/civil-defense-shelters/source-identity/sha256-${SOURCE_SHA256}`;
const MANIFEST_URL = "/__local-research-owner-only/civil-defense-shelters/manifest.json";
const fields: readonly DatasetField[] = [
  { name: "record_id", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "entity_id", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "name", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "capacity", type: "string", nullable: false, nullMeaning: null, unit: "source_reported_person_capacity" }, { name: "district", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "subtype", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "facility_subtype", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "source", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "source_tier", type: "number", nullable: false, nullMeaning: null, unit: null }, { name: "coord_source", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "coord_suspect", type: "boolean", nullable: false, nullMeaning: null, unit: "true_when_coordinate_is_suspect" }, { name: "coord_precision", type: "string", nullable: false, nullMeaning: null, unit: "exact_or_approximation_category" }, { name: "coord_shared_n", type: "number", nullable: false, nullMeaning: null, unit: "records_sharing_coordinate" }, { name: "source_count", type: "number", nullable: false, nullMeaning: null, unit: "source_count" }, { name: "fetched_at", type: "string", nullable: false, nullMeaning: null, unit: "ISO-8601_date" }, { name: "geometry", type: "json", nullable: false, nullMeaning: null, unit: null },
];
export const civilDefenseSheltersOwnerDescriptor: DatasetDescriptor = {
  schemaVersion: "pulse-dataset/0.1", datasetId: "tw-civil-defense-shelters-20260824-owner-only", label: "防空疏散避難設施（2026-08-24 owner-only）", description: "15 個來源併源的 110,291 個防空疏散避難設施固定快照。每次必須給 bbox，只讀 immutable gzip 分片；座標是參考位置，不能回答最近、可用、開放、容量可用性、避難安全或道路可達性。",
  layerRefs: ["civilDefenseShelter"], kind: "point", recordGrain: "place", primaryKey: ["record_id"], fields, geometry: { type: "Point", crs: "EPSG:4326", role: "proxy", precision: "14 公開名冊與 TGOS 主題 API 併源的 reference Point。exact 102,577、street_block 1,843、approximate 5,871；coord_suspect 1,753。TGOS 有路段 fallback，Point 不代表入口、實際避難位置、可用容量、當前開放或安全通行。", spatialAnalysisEligible: false }, timeFields: [], coverage: "2026-08-24 完整重建：14 公開名冊加 TGOS 共 15 source、110,291 canonical 點。舊版 62,695 僅六都且不能與此版混用。全部是防空設施名冊，非天災避難收容所；coord_suspect 與 approximate 均保留，不能視為無資料或零設施。", license: "RIGHTS_HOLD: 14 個公開名冊標示 OGDL-Taiwan-1.0，但 TGOS 原始座標的公開再散布權利仍 HOLD；只供本機 owner-only。", valueSemantics: { ...DEFAULT_VALUE_SEMANTICS, missing: "bbox 無結果或本 Point 側無列不代表該地沒有可用避難設施。", stale: "2026-08-24 快照不代表目前開放、容量、可用性、風險或避難指示。" }, versions: [{ versionId: `20260824-geojson-sha256:${SOURCE_SHA256}`, observedAt: null, availableAt: "2026-08-24T00:00:00+08:00", checksumSha256: SOURCE_SHA256, mutable: false }], source: { publisher: "內政部警政署／14 個 data.gov.tw 名冊與 TGOS 內政主題 API", reference: SOURCE_REFERENCE, lineage: "14 public rosters + TGOS Theme_Id=amk94aCG -> address/trust-chain merge -> 110,291-point processed GeoJSON SHA a3ab…2aae -> owner-only safe-field source-SHA-bound gzip partitions. Address, normalized address, confidence and raw provenance list are omitted." }, access: boundedAccess({ mode: "owner_only", method: "pmtiles_sidecar", fields: fields.map(field => field.name), filters: fields.filter(field => !["record_id", "geometry"].includes(field.name)).map(field => field.name), supportsBbox: true, maxRowsPerQuery: 100, maxScanRows: 20_000, maxSourceBytes: 8 * 1024 * 1024 }), supportedOperations: ["query_records", "aggregate"], adapterId: "civil-defense-shelters-owner-reference-partitions-v1",
};
function fail(code: string): never { throw new Error(code); }
async function readCivilDefenseShelters(_parameters: Readonly<Record<string, Scalar>>, signal?: AbortSignal, context?: { bbox?: readonly [number, number, number, number] }): Promise<AdapterSnapshot> { if (!context?.bbox) fail("BBOX_REQUIRED"); const snapshot = await loadPointDataset({ datasetId: civilDefenseSheltersOwnerDescriptor.datasetId, url: SOURCE_REFERENCE, idField: "entity_id", safeFields: fields.map(field => field.name).filter(name => !["record_id", "geometry"].includes(name)), spatialPartition: { manifestUrl: MANIFEST_URL, manifestSha256: MANIFEST_SHA256, sourceSha256: SOURCE_SHA256 } }, { bbox: context.bbox, signal }); if (snapshot.checksumSha256 !== SOURCE_SHA256 || snapshot.exclusions.missing_geometry || snapshot.exclusions.non_point_geometry || snapshot.exclusions.invalid_geometry) fail("CIVIL_DEFENSE_SHELTER_SOURCE_SEMANTICS_MISMATCH"); const source: SourceReceipt = { sourceId: civilDefenseSheltersOwnerDescriptor.datasetId, version: `sha256:${SOURCE_SHA256}`, acquiredAt: snapshot.acquiredAt, checksumSha256: SOURCE_SHA256, reference: SOURCE_REFERENCE }; return { rows: snapshot.rows, source, coverage: civilDefenseSheltersOwnerDescriptor.coverage, freshness: "unknown", exclusions: { coord_suspect: 1_753, coord_precision_street_block: 1_843, coord_precision_approximate: 5_871, ...snapshot.exclusions }, rowsScanned: snapshot.rows.length, bytesScanned: snapshot.bytes, downloadedBytes: snapshot.downloadedBytes, requests: snapshot.requests, cacheHit: snapshot.cacheHit }; }
export const civilDefenseSheltersOwnerAdapter = createReferencePointDatasetAdapter(civilDefenseSheltersOwnerDescriptor, readCivilDefenseShelters);
