import { boundedAccess, DEFAULT_VALUE_SEMANTICS, type DatasetDescriptor, type DatasetField, type Scalar, type SourceReceipt } from "./dataContracts";
import type { AdapterReadResult, QueryAdapter } from "./queryExecutor";
import { geometriesIntersect, parseSpatialGeometry, type PolygonGeometry } from "./spatialKernel";
import { withLoading } from "../lib/loadingRegistry";

type Bbox = readonly [number, number, number, number];
type Scale = 450 | 1500;
type Family = "industry" | "age";
interface Shard { path: string; sha256: string; bytes: number; encoding: "gzip"; uncompressedSha256: string; uncompressedBytes: number; featureCount: number; bbox: Bbox; }
interface Manifest { schemaVersion: "pulse-company-demographics-owner-surface-partitions/1"; source: { sha256: string; bytes: number; featureCount: number; reference: string }; grid: { size_m: number; crs_projected: string; crs_output: string; occupied_only: boolean }; shards: readonly Shard[]; }

const MAX_BYTES = 8 * 1024 * 1024, MAX_ROWS = 20_000;
const INDUSTRY_CODES = ["01", "02", "03", "05", "06", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "41", "42", "43", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "58", "59", "60", "61", "62", "63", "64", "65", "66", "67", "68", "69", "70", "71", "72", "73", "74", "75", "76", "77", "78", "79", "80", "81", "82", "83", "85", "86", "87", "88", "90", "91", "92", "93", "94", "95", "96"] as const;
const INDUSTRY_FIELDS = [...INDUSTRY_CODES.map(code => `i_${code}`), "i_unknown"] as const;
const AGE_FIELDS = ["age_known", "age_missing", "age_invalid", "age_recent", "age_median", "age_0_2", "age_3_5", "age_6_10", "age_11_20", "age_21_plus"] as const;
const SOURCE: Record<Scale, { sha256: string; count: number; manifestSha: string }> = {
  450: { sha256: "9f97d9d0e6747af17493109a43c1c42a64bae55c47b90e519ad8045c0c2918cd", count: 26_834, manifestSha: "7fe4ed971dd4a7bcc34ce6954567a260459e5f74b5fe366fc6d2370f5276b071" },
  1500: { sha256: "cc71991553954c95085476508c3ec64c989f47d195b2bccc25ed084bdd33b429", count: 5_745, manifestSha: "b67714c49531774daad010a490fc05e6368cf4ea3af5c5c8e70db06f69d8d4b6" },
};
const BASE = "/__local-research-owner-only/company-demographics/";
const baseFields: readonly DatasetField[] = [{ name: "grid_id", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "n_companies", type: "number", nullable: false, nullMeaning: null, unit: "companies" }];
const industryFields: readonly DatasetField[] = [...baseFields, ...INDUSTRY_FIELDS.map(name => ({ name, type: "number" as const, nullable: false, nullMeaning: null, unit: "companies" })), { name: "geometry", type: "json", nullable: false, nullMeaning: null, unit: null }];
const ageFields: readonly DatasetField[] = [...baseFields, { name: "age_known", type: "number", nullable: false, nullMeaning: null, unit: "companies" }, { name: "age_missing", type: "number", nullable: false, nullMeaning: null, unit: "companies" }, { name: "age_invalid", type: "number", nullable: false, nullMeaning: null, unit: "companies" }, { name: "age_recent", type: "number", nullable: false, nullMeaning: null, unit: "companies" }, { name: "age_median", type: "number", nullable: true, nullMeaning: "No valid setup year in this occupied cell; it is not age zero.", unit: "years" }, ...["age_0_2", "age_3_5", "age_6_10", "age_11_20", "age_21_plus"].map(name => ({ name, type: "number" as const, nullable: false, nullMeaning: null, unit: "companies" })), { name: "geometry", type: "json", nullable: false, nullMeaning: null, unit: null }];

function descriptor(family: Family, scale: Scale): DatasetDescriptor {
  const source = SOURCE[scale], title = family === "industry" ? "公司登記產業分布" : "公司設立年齡結構";
  return { schemaVersion: "pulse-dataset/0.1", datasetId: `tw-company-${family}-grid-${scale}m-owner-202608`, label: `${title} ${scale}m 格網（202608 owner-only）`,
    description: `GCIS 202608 固定快照的 ${source.count.toLocaleString()} 個 occupied-only ${scale}m Polygon 格網。bbox 必填，僅讀取相交 checksum-bound gzip 分片後以完整 Polygon 判斷。${family === "industry" ? "產業是第一順位兩碼行業聚合，並不代表實際主營產業。" : "設立年缺失、無效與已知值分開保留。"}`,
    layerRefs: [family === "industry" ? "companyIndustryDistribution" : "companyAgeStructure"], kind: "grid", recordGrain: "grid_cell", primaryKey: ["grid_id"], fields: family === "industry" ? industryFields : ageFields,
    geometry: { type: "Polygon", crs: "EPSG:4326", role: "generalized", precision: `EPSG:3826 canonical ${scale}m occupied-only grid transformed to WGS84; full source cell boundary, not a company premise, Point, or administrative boundary.`, spatialAnalysisEligible: false },
    timeFields: [], coverage: `202608 fixed snapshot: 657,882 source rows, excluding dead_or_abnormal 1,152 and invalid_coordinate 2,565, then 654,165 company-registration points aggregated into ${source.count.toLocaleString()} nonempty ${scale}m occupied-only cells. setup_year missing=16 and invalid=0 remain represented in age_missing/age_invalid, rather than exclusions. An omitted cell is not a zero-company observation.`,
    license: "RIGHTS_HOLD for public redistribution: processed source records OGDL-Taiwan-1.0, but the 118-member upstream company_stock source-matrix receipts have not all been rechecked. Localhost owner-only only.",
    valueSemantics: { ...DEFAULT_VALUE_SEMANTICS, missing: family === "age" ? "age_median=null means no valid setup year in that occupied cell; it is not age zero. age_missing is setup_year=null; age_invalid is a non-null setup_year outside 1911..2026. An absent cell is not zero companies." : "A missing cell is not zero companies; each emitted i_* count is explicit and i_unknown remains separate.", zero: "An explicit zero count is zero for that category in an occupied cell, not a missing value.", stale: "202608 is a fixed monthly snapshot and does not establish current company existence, operation, address presence, or accessibility." },
    versions: [{ versionId: `202608-grid${scale}-source-sha256:${source.sha256}`, observedAt: null, availableAt: "2026-09-10", checksumSha256: source.sha256, mutable: false }],
    source: { publisher: "經濟部商業發展署 GCIS", reference: `/research/company-demographics-grid-${scale}m/source-identity/sha256-${source.sha256}`, lineage: "118 regional×industry company_stock source matrix -> 202608 company_points (654,165 released points) -> status/coordinate exclusions -> EPSG:3826 150m grid -> nested 450m/1500m aggregation -> source-SHA-bound safe-field localhost owner-only surface partitions. No individual company identifier, name, address, responsible person, or Point is materialized." },
    access: boundedAccess({ mode: "owner_only", method: "local_asset", fields: (family === "industry" ? industryFields : ageFields).map(field => field.name), filters: ["grid_id"], supportsBbox: true, maxRowsPerQuery: 100, maxScanRows: MAX_ROWS, maxSourceBytes: MAX_BYTES }), supportedOperations: ["query_records", "aggregate"], adapterId: `company-${family}-grid-owner-${scale}m-partitions-v1` };
}
export const companyIndustryDistribution450mOwnerDescriptor = descriptor("industry", 450);
export const companyIndustryDistribution1500mOwnerDescriptor = descriptor("industry", 1500);
export const companyAgeStructure450mOwnerDescriptor = descriptor("age", 450);
export const companyAgeStructure1500mOwnerDescriptor = descriptor("age", 1500);
function fail(code: string): never { throw new Error(code); }
function validBbox(value: unknown): value is Bbox { return Array.isArray(value) && value.length === 4 && value.every(item => typeof item === "number" && Number.isFinite(item)) && value[0]! <= value[2]! && value[1]! <= value[3]!; }
function intersects(left: Bbox, right: Bbox): boolean { return left[0] <= right[2] && left[2] >= right[0] && left[1] <= right[3] && left[3] >= right[1]; }
function surface([west, south, east, north]: Bbox): PolygonGeometry { return { type: "Polygon", coordinates: [[[west, south], [east, south], [east, north], [west, north], [west, south]]] }; }
async function sha256(value: Uint8Array): Promise<string> { const digest = await crypto.subtle.digest("SHA-256", value); return [...new Uint8Array(digest)].map(byte => byte.toString(16).padStart(2, "0")).join(""); }
async function bounded(response: Response): Promise<Uint8Array> { const length = Number(response.headers.get("content-length")); if (Number.isFinite(length) && length > MAX_BYTES) fail("DATASET_TOO_LARGE"); const value = new Uint8Array(await response.arrayBuffer()); if (value.byteLength > MAX_BYTES) fail("DATASET_TOO_LARGE"); return value; }
async function fetchChecked(url: string, expected: string, signal?: AbortSignal): Promise<Uint8Array> { const response = await fetch(url, { credentials: "same-origin", redirect: "error", signal: signal ?? AbortSignal.timeout(15_000) }); if (!response.ok || !response.body) fail("COMPANY_DEMOGRAPHICS_OWNER_ASSET_UNAVAILABLE"); const value = await bounded(response); if (await sha256(value) !== expected) fail("COMPANY_DEMOGRAPHICS_OWNER_ASSET_MISMATCH"); return value; }
async function decode(shard: Shard, compressed: Uint8Array): Promise<Uint8Array> { if (typeof DecompressionStream === "undefined") fail("COMPRESSION_UNSUPPORTED"); const response = new Response(new Blob([compressed]).stream().pipeThrough(new DecompressionStream("gzip"))); const value = await bounded(response); if (value.byteLength !== shard.uncompressedBytes || await sha256(value) !== shard.uncompressedSha256) fail("COMPANY_DEMOGRAPHICS_OWNER_PARTITION_MISMATCH"); return value; }
function manifestFor(value: unknown, scale: Scale): Manifest { const source = SOURCE[scale], item = value as Partial<Manifest>; if (!item || typeof item !== "object" || item.schemaVersion !== "pulse-company-demographics-owner-surface-partitions/1" || item.source?.sha256 !== source.sha256 || item.source.featureCount !== source.count || item.source.reference !== `/research/company-demographics-grid-${scale}m/source-identity/sha256-${source.sha256}` || item.grid?.size_m !== scale || item.grid.crs_projected !== "EPSG:3826" || item.grid.crs_output !== "EPSG:4326" || item.grid.occupied_only !== true || !Array.isArray(item.shards) || !item.shards.length || item.shards.length > 1024) fail("COMPANY_DEMOGRAPHICS_OWNER_MANIFEST_INVALID"); const paths = new Set<string>(); let declared = 0; for (const shard of item.shards) { if (!shard || shard.encoding !== "gzip" || !new RegExp(`^${shard.sha256}-[a-f0-9]+\\.geojson\\.gz$`).test(shard.path) || !/^[a-f0-9]{64}$/.test(shard.sha256) || !/^[a-f0-9]{64}$/.test(shard.uncompressedSha256) || !Number.isSafeInteger(shard.bytes) || shard.bytes < 1 || !Number.isSafeInteger(shard.uncompressedBytes) || shard.uncompressedBytes < 1 || shard.uncompressedBytes > MAX_BYTES || !Number.isSafeInteger(shard.featureCount) || shard.featureCount < 1 || shard.featureCount > MAX_ROWS || !validBbox(shard.bbox) || paths.has(shard.path)) fail("COMPANY_DEMOGRAPHICS_OWNER_MANIFEST_INVALID"); paths.add(shard.path); declared += shard.featureCount; } if (declared < source.count) fail("COMPANY_DEMOGRAPHICS_OWNER_MANIFEST_INVALID"); return item as Manifest; }
function parsedRow(feature: unknown, ordinals: Set<number>, scale: Scale, shardBbox: Bbox, family: Family): Record<string, unknown> | null { const item = feature as { type?: unknown; sourceOrdinal?: unknown; properties?: Record<string, unknown>; geometry?: unknown }, p = item?.properties, ordinal = item?.sourceOrdinal; const numeric = [...INDUSTRY_FIELDS, ...AGE_FIELDS.filter(field => field !== "age_median")]; if (item?.type !== "Feature" || !Number.isSafeInteger(ordinal) || (ordinal as number) < 0 || (ordinal as number) >= SOURCE[scale].count || !p || typeof p.grid_id !== "string" || !new RegExp(`^G${scale}_-?\\d+_-?\\d+$`).test(p.grid_id) || !Number.isSafeInteger(p.n_companies) || (p.n_companies as number) < 1 || numeric.some(field => !Number.isSafeInteger(p[field]) || (p[field] as number) < 0) || !(p.age_median === null || typeof p.age_median === "number" && Number.isFinite(p.age_median) && p.age_median >= 0)) fail("COMPANY_DEMOGRAPHICS_OWNER_ROW_INVALID"); const industry = INDUSTRY_FIELDS.reduce((total, field) => total + (p[field] as number), 0), ageBuckets = (p.age_0_2 as number) + (p.age_3_5 as number) + (p.age_6_10 as number) + (p.age_11_20 as number) + (p.age_21_plus as number); if (industry !== p.n_companies || (p.age_known as number) + (p.age_missing as number) + (p.age_invalid as number) !== p.n_companies || ageBuckets !== p.age_known || ((p.age_known as number) === 0) !== (p.age_median === null)) fail("COMPANY_DEMOGRAPHICS_OWNER_ROW_CONSERVATION_MISMATCH"); const geometry = parseSpatialGeometry(item.geometry); if (geometry.type !== "Polygon" || !geometriesIntersect(geometry, surface(shardBbox))) fail("COMPANY_DEMOGRAPHICS_OWNER_PARTITION_SCOPE_INVALID"); if (ordinals.has(ordinal as number)) return null; ordinals.add(ordinal as number); const keys = family === "industry" ? ["grid_id", "n_companies", ...INDUSTRY_FIELDS] : ["grid_id", "n_companies", ...AGE_FIELDS]; return Object.fromEntries([...keys.map(key => [key, p[key]]), ["geometry", geometry]]); }
function currentDescriptor(family: Family, scale: Scale): DatasetDescriptor { return family === "industry" ? scale === 450 ? companyIndustryDistribution450mOwnerDescriptor : companyIndustryDistribution1500mOwnerDescriptor : scale === 450 ? companyAgeStructure450mOwnerDescriptor : companyAgeStructure1500mOwnerDescriptor; }
async function read(family: Family, scale: Scale, context?: { bbox?: Bbox }, signal?: AbortSignal): Promise<AdapterReadResult> { if (!context?.bbox) fail("BBOX_REQUIRED"); const source = SOURCE[scale], descriptor = currentDescriptor(family, scale); return withLoading(`research:company-${family}-${scale}m`, descriptor.label, (async () => { const manifestBytes = await fetchChecked(`${BASE}manifest-${scale}m.json`, source.manifestSha, signal), manifest = manifestFor(JSON.parse(new TextDecoder().decode(manifestBytes)), scale), selected = manifest.shards.filter(shard => intersects(shard.bbox, context.bbox!)), rowsScanned = selected.reduce((total, shard) => total + shard.featureCount, 0), declaredBytes = manifestBytes.byteLength + selected.reduce((total, shard) => total + shard.uncompressedBytes, 0); if (rowsScanned > MAX_ROWS || declaredBytes > MAX_BYTES) fail("SCAN_BUDGET_EXCEEDED"); const ordinals = new Set<number>(), rows: Record<string, unknown>[] = []; let bytesScanned = manifestBytes.byteLength; for (const shard of selected) { const decoded = await decode(shard, await fetchChecked(`${BASE}${shard.path}`, shard.sha256, signal)); bytesScanned += decoded.byteLength; const collection = JSON.parse(new TextDecoder().decode(decoded)) as { type?: unknown; features?: unknown }; if (collection.type !== "FeatureCollection" || !Array.isArray(collection.features) || collection.features.length !== shard.featureCount) fail("COMPANY_DEMOGRAPHICS_OWNER_PARTITION_INVALID"); for (const feature of collection.features) { const row = parsedRow(feature, ordinals, scale, shard.bbox, family); if (row) rows.push(row); } } const receipt: SourceReceipt = { sourceId: descriptor.datasetId, version: `sha256:${source.sha256}`, checksumSha256: source.sha256, reference: descriptor.source.reference, acquiredAt: new Date().toISOString() }; return { rows, sourceRefs: [receipt], coverage: descriptor.coverage, freshness: "stale", exclusions: { dead_or_abnormal: 1_152, invalid_coordinate: 2_565 }, rowsScanned, bytesScanned, downloadedBytes: bytesScanned, requests: selected.length + 1, cacheHit: false, expiresAt: null }; })()); }
function adapter(family: Family, scale: Scale): QueryAdapter { const descriptor = currentDescriptor(family, scale); return { descriptor, allowedParameters: {}, read: (_parameters: Readonly<Record<string, Scalar>>, signal, context) => read(family, scale, context, signal) }; }
export const companyIndustryDistribution450mOwnerAdapter = adapter("industry", 450);
export const companyIndustryDistribution1500mOwnerAdapter = adapter("industry", 1500);
export const companyAgeStructure450mOwnerAdapter = adapter("age", 450);
export const companyAgeStructure1500mOwnerAdapter = adapter("age", 1500);
