import { boundedAccess, DEFAULT_VALUE_SEMANTICS, type DatasetDescriptor, type DatasetField, type Scalar, type SourceReceipt } from "./dataContracts";
import { loadPointDataset } from "./pointDatasetAdapter";
import { createReferencePointDatasetAdapter, type AdapterSnapshot } from "./queryAdapters";

type Spec = Readonly<{ key: "kindergarten" | "afterschoolCare" | "mutualCare"; datasetId: string; label: string; layerRef: "eduKindergarten" | "eduAfterschoolCare" | "eduMutualCare"; url: string; sha: string; rows: number; points: number; unlocated: number; safeFields: readonly string[]; coverage: string; source: string }>;
const specs: readonly Spec[] = [
  { key: "kindergarten", datasetId: "tw-kindergartens-owner-20260807", label: "全國幼兒園名冊（owner-only 2026-08-07）", layerRef: "eduKindergarten", url: "/__local-research-owner-only/education-childcare/kindergartens-20260807-owner.geojson", sha: "af274b24b8d723529a3f3d5321b2f1d1f9fbb3514d855c2810fdcad3ea1c1e9a", rows: 6747, points: 6689, unlocated: 58, safeFields: ["source_row_id", "academic_year", "code", "name", "ownership", "city", "district", "coordinate_status", "geocode_source", "geocode_precision"], coverage: "114 學年度 6,747 筆：6,689 Point，58 筆 geocode miss 保留為 geometry=null。", source: "教育部統計處 k1_new.csv" },
  { key: "afterschoolCare", datasetId: "tw-afterschool-care-owner-20260807", label: "全國立案兒童課後照顧服務中心（owner-only 2026-08-07）", layerRef: "eduAfterschoolCare", url: "/__local-research-owner-only/education-childcare/afterschool-care-20260807-owner.geojson", sha: "8d397b57b7e0626709ff26294137fb93f4693708cf3edba058bf3e62ddf7098d", rows: 787, points: 782, unlocated: 5, safeFields: ["source_row_id", "name", "city", "registered_at", "coordinate_status", "geocode_source", "geocode_precision"], coverage: "固定名冊 787 筆：782 Point，5 筆 geocode miss 保留為 geometry=null。", source: "教育部 afterschool.moe.gov.tw opendata.csv" },
  { key: "mutualCare", datasetId: "tw-mutual-care-owner-20260807", label: "互助教保服務中心名冊（owner-only 2026-08-07）", layerRef: "eduMutualCare", url: "/__local-research-owner-only/education-childcare/mutual-care-20260807-owner.geojson", sha: "831487177df0821dae8d7cdae49f3fa20f7a1283fd97aacd5f7b0e371c7276a0", rows: 148, points: 148, unlocated: 0, safeFields: ["source_row_id", "sequence", "academic_year", "school_code", "name", "ownership", "city_code", "city", "district", "coordinate_status", "geocode_source", "geocode_precision"], coverage: "114 學年度 148 筆，全部為 Point。", source: "教育部統計處 k2_new.csv" },
];
const baseFields: readonly DatasetField[] = [
  { name: "record_id", type: "string", nullable: false, nullMeaning: null, unit: null },
  { name: "source_row_id", type: "string", nullable: false, nullMeaning: null, unit: null },
  { name: "name", type: "string", nullable: false, nullMeaning: null, unit: null },
  { name: "city", type: "string", nullable: false, nullMeaning: null, unit: null },
  { name: "coordinate_status", type: "string", nullable: false, nullMeaning: null, unit: null },
  { name: "geocode_source", type: "string", nullable: true, nullMeaning: "未定位列的 null；不是零座標或未知地點。", unit: null },
  { name: "geocode_precision", type: "string", nullable: true, nullMeaning: "未定位列沒有定位精度。", unit: null },
  { name: "geometry", type: "json", nullable: true, nullMeaning: "geocode miss 仍保留原表安全屬性，但不會出現在 bbox 結果。", unit: null },
];
const extraFields: Readonly<Record<string, DatasetField>> = {
  academic_year: { name: "academic_year", type: "number", nullable: false, nullMeaning: null, unit: "academic_year" }, code: { name: "code", type: "string", nullable: false, nullMeaning: null, unit: null }, ownership: { name: "ownership", type: "string", nullable: false, nullMeaning: null, unit: null }, district: { name: "district", type: "string", nullable: false, nullMeaning: null, unit: null }, registered_at: { name: "registered_at", type: "string", nullable: false, nullMeaning: null, unit: "ROC_yyyMMdd" }, sequence: { name: "sequence", type: "number", nullable: false, nullMeaning: null, unit: "source_sequence" }, school_code: { name: "school_code", type: "string", nullable: false, nullMeaning: null, unit: null }, city_code: { name: "city_code", type: "number", nullable: false, nullMeaning: null, unit: "source_city_code" },
};
function fail(code: string): never { throw new Error(code); }
function createDataset(spec: Spec) {
  const fields = [...baseFields.filter(field => ["record_id", "source_row_id", "name", "city", "coordinate_status", "geocode_source", "geocode_precision", "geometry"].includes(field.name)), ...spec.safeFields.filter(name => name in extraFields).map(name => extraFields[name]!)];
  const descriptor: DatasetDescriptor = { schemaVersion: "pulse-dataset/0.1", datasetId: spec.datasetId, label: spec.label, description: `${spec.coverage} 來源以 offline cache、TGOS 或內插取得的參考座標，僅限 owner-only。`, layerRefs: [spec.layerRef], kind: "point", recordGrain: "place", primaryKey: ["record_id"], fields, geometry: { type: "Point", crs: "EPSG:4326", role: "proxy", precision: "Point 是地址地理編碼結果，且含 exact、cached、tgos、interpolated；只能作 bbox 與屬性參考，不能主張最近、距離、入口、服務範圍或道路可達性。", spatialAnalysisEligible: false }, timeFields: [], coverage: `${spec.coverage} 這是 2026-08-07 處理快照，不代表目前立案、招生、開放、服務量能或存續狀態。`, license: "OGDL-Taiwan-1.0 原始名冊；sidecar 含 geocode 參考座標，公開再散布權利未逐列核對，僅限 owner-only。", valueSemantics: { ...DEFAULT_VALUE_SEMANTICS, null: "geometry、geocode_source 與 geocode_precision 的 null 表示該列未被地理編碼；不是不存在、零值或可由行政區中心補點。", stale: "2026-08-07 固定處理快照不是目前立案、招生、開放或服務狀態。" }, versions: [{ versionId: `sha256:${spec.sha}`, observedAt: null, availableAt: "2026-08-07T00:00:00+08:00", checksumSha256: spec.sha, mutable: false }], source: { publisher: spec.source, reference: spec.url, lineage: `${spec.source} -> taipei-gis-analytics 20260807 processed GeoJSON + _geocode_miss.csv -> 安全欄位 owner-only sidecar；sidecar 移除地址、電話與 address_clean。` }, access: boundedAccess({ mode: "owner_only", method: "local_asset", fields: fields.map(field => field.name), filters: fields.filter(field => !["record_id", "geometry"].includes(field.name)).map(field => field.name), supportsBbox: true, maxRowsPerQuery: 100, maxScanRows: spec.rows, maxSourceBytes: 6 * 1024 * 1024 }), supportedOperations: ["query_records", "aggregate"], adapterId: `education-childcare-${spec.key}-owner-reference-v1` };
  const read = async (_parameters: Readonly<Record<string, Scalar>>, signal?: AbortSignal): Promise<AdapterSnapshot> => { const snapshot = await loadPointDataset({ datasetId: descriptor.datasetId, url: spec.url, idField: "source_row_id", safeFields: spec.safeFields, preserveUnlocatedRecords: true }, { signal }); if (snapshot.checksumSha256 !== spec.sha) fail(`EDUCATION_CHILDCARE_${spec.key}_OWNER_SOURCE_SHA_MISMATCH`); if (snapshot.rows.length !== spec.rows || snapshot.exclusions.missing_geometry !== spec.unlocated || snapshot.exclusions.non_point_geometry !== 0 || snapshot.exclusions.invalid_geometry !== 0) fail(`EDUCATION_CHILDCARE_${spec.key}_OWNER_SOURCE_SEMANTICS_MISMATCH`); const source: SourceReceipt = { sourceId: descriptor.datasetId, version: `sha256:${spec.sha}`, acquiredAt: snapshot.acquiredAt, checksumSha256: spec.sha, reference: spec.url }; return { rows: snapshot.rows, source, coverage: descriptor.coverage, freshness: "unknown", exclusions: snapshot.exclusions, rowsScanned: snapshot.rows.length, bytesScanned: snapshot.bytes, downloadedBytes: snapshot.downloadedBytes, requests: snapshot.requests, cacheHit: snapshot.cacheHit }; };
  return { descriptor, adapter: createReferencePointDatasetAdapter(descriptor, read) };
}
const kindergarten = createDataset(specs[0]!); const afterschoolCare = createDataset(specs[1]!); const mutualCare = createDataset(specs[2]!);
export const educationKindergartenOwnerDescriptor = kindergarten.descriptor; export const educationKindergartenOwnerAdapter = kindergarten.adapter;
export const educationAfterschoolCareOwnerDescriptor = afterschoolCare.descriptor; export const educationAfterschoolCareOwnerAdapter = afterschoolCare.adapter;
export const educationMutualCareOwnerDescriptor = mutualCare.descriptor; export const educationMutualCareOwnerAdapter = mutualCare.adapter;
