import { boundedAccess, DEFAULT_VALUE_SEMANTICS, type DatasetDescriptor, type DatasetField, type Scalar, type SourceReceipt } from "./dataContracts";
import type { AdapterReadResult, QueryAdapter } from "./queryExecutor";
import { withLoading } from "../lib/loadingRegistry";

const URL = "/__local-research-owner-only/forest-recreation/forest-recreation-owner-1151.geojson";
const SHA256 = "815448720c3c12d2ae41898a445f6f4c42fb86e9f1f4a9c9cc0dea8d9580cacc";
const MAX_BYTES = 8 * 1024 * 1024;
const fields: readonly DatasetField[] = [{ name: "ename", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "park", type: "string", nullable: true, nullMeaning: "Source does not name a sub-park.", unit: null }, { name: "district_code", type: "string", nullable: true, nullMeaning: "Source does not provide a district code.", unit: null }, { name: "area_ha", type: "number", nullable: false, nullMeaning: null, unit: "ha" }, { name: "geometry", type: "json", nullable: false, nullMeaning: null, unit: null }];
export const forestRecreationOwnerDescriptor: DatasetDescriptor = { schemaVersion: "pulse-dataset/0.1", datasetId: "tw-forest-recreation-areas-owner-1151", label: "國家森林遊樂區範圍（1151 owner-only）", description: "林業及自然保育署 data.gov.tw 9931 的 23 筆指定森林遊樂區 Polygon/MultiPolygon 固定快照。bbox 可對完整面界做相交查詢；不是入口、步道、設施、開放狀態、可進入性或服務範圍。", layerRefs: ["forestRecreation"], kind: "polygon", recordGrain: "feature", primaryKey: ["ename", "park"], fields, geometry: { type: "MultiPolygon", crs: "EPSG:4326", role: "actual", precision: "Complete source Polygon and MultiPolygon boundaries are retained; Polygon records are represented as one-part MultiPolygon for a consistent full-surface reader.", spatialAnalysisEligible: true }, timeFields: [], coverage: "23 designated forest recreation-area source features: 19 Polygon and 4 MultiPolygon. park=null and district_code=null are source missing values; an absent feature or area is not evidence that recreation, access, or a forest boundary is absent.", license: "OGDL-Taiwan-1.0; source: 農業部林業及自然保育署 data.gov.tw dataset 9931; localhost owner-only reader.", valueSemantics: { ...DEFAULT_VALUE_SEMANTICS, missing: "park/district_code null is a source missing attribute, not an empty or unknown recreation boundary.", stale: "1151 source edition and 2026-05-19 processed snapshot do not establish current opening, closure, access, safety, facilities, or trail conditions." }, versions: [{ versionId: "1151-processed-sha256:bb7e1604918d3329e554c44788f9c376985f4c4707ae37d19cb0aedb0dd49c05", observedAt: null, availableAt: "2026-05-19", checksumSha256: "bb7e1604918d3329e554c44788f9c376985f4c4707ae37d19cb0aedb0dd49c05", mutable: false }], source: { publisher: "農業部林業及自然保育署", reference: "https://data.gov.tw/dataset/9931", lineage: "1151 source SHP/KML/ZIP -> processed EPSG:4326 GeoJSON sha256:bb7e1604918d3329e554c44788f9c376985f4c4707ae37d19cb0aedb0dd49c05 -> safe-field localhost owner-only asset." }, access: boundedAccess({ mode: "owner_only", method: "local_asset", fields: fields.map(field => field.name), filters: ["ename", "park", "district_code"], supportsBbox: true, maxRowsPerQuery: 23, maxScanRows: 23, maxSourceBytes: MAX_BYTES }), supportedOperations: ["query_records"], adapterId: "forest-recreation-owner-surfaces-v1" };
function fail(code: string): never { throw new Error(code); }
async function digest(bytes: Uint8Array): Promise<string> { const value = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(value)].map(byte => byte.toString(16).padStart(2, "0")).join(""); }
function multi(geometry: unknown): Record<string, unknown> { const item = geometry as { type?: unknown; coordinates?: unknown }; if (item?.type === "Polygon") return { type: "MultiPolygon", coordinates: [item.coordinates] }; if (item?.type === "MultiPolygon") return { type: "MultiPolygon", coordinates: item.coordinates }; fail("FOREST_RECREATION_OWNER_GEOMETRY_INVALID"); }
async function read(signal?: AbortSignal): Promise<AdapterReadResult> { return withLoading("research:forest-recreation-owner", "國家森林遊樂區範圍", (async () => { const response = await fetch(URL, { credentials: "same-origin", redirect: "error", signal: signal ?? AbortSignal.timeout(15_000) }); if (!response.ok || !response.body) fail("FOREST_RECREATION_OWNER_ASSET_UNAVAILABLE"); const declared = Number(response.headers.get("content-length")); if (Number.isFinite(declared) && declared > MAX_BYTES) fail("FOREST_RECREATION_OWNER_ASSET_MISMATCH"); const bytes = new Uint8Array(await response.arrayBuffer()); if (bytes.byteLength > MAX_BYTES || await digest(bytes) !== SHA256) fail("FOREST_RECREATION_OWNER_ASSET_MISMATCH"); const collection = JSON.parse(new TextDecoder().decode(bytes)) as { type?: unknown; features?: unknown[] }; if (collection.type !== "FeatureCollection" || !Array.isArray(collection.features) || collection.features.length !== 23) fail("FOREST_RECREATION_OWNER_COLLECTION_INVALID"); const ids = new Set<string>(), rows = collection.features.map((raw, ordinal) => { const feature = raw as { type?: unknown; sourceOrdinal?: unknown; properties?: Record<string, unknown>; geometry?: unknown }, p = feature.properties; if (feature.type !== "Feature" || feature.sourceOrdinal !== ordinal || !p || typeof p.ename !== "string" || !p.ename || !(p.park === null || typeof p.park === "string") || !(p.district_code === null || typeof p.district_code === "string") || typeof p.area_ha !== "number" || !Number.isFinite(p.area_ha) || p.area_ha < 0) fail("FOREST_RECREATION_OWNER_ROW_INVALID"); const id = `${p.ename}\u0000${p.park ?? ""}`; if (ids.has(id)) fail("FOREST_RECREATION_OWNER_DUPLICATE_ID"); ids.add(id); return { ename: p.ename, park: p.park, district_code: p.district_code, area_ha: p.area_ha, geometry: multi(feature.geometry) }; }); const receipt: SourceReceipt = { sourceId: forestRecreationOwnerDescriptor.datasetId, version: "processed-sha256:bb7e1604918d3329e554c44788f9c376985f4c4707ae37d19cb0aedb0dd49c05", checksumSha256: "bb7e1604918d3329e554c44788f9c376985f4c4707ae37d19cb0aedb0dd49c05", reference: forestRecreationOwnerDescriptor.source.reference, acquiredAt: new Date().toISOString() }; return { rows, sourceRefs: [receipt], coverage: forestRecreationOwnerDescriptor.coverage, freshness: "stale", exclusions: {}, rowsScanned: 23, bytesScanned: bytes.byteLength, downloadedBytes: bytes.byteLength, requests: 1, cacheHit: false, expiresAt: null }; })()); }
export const forestRecreationOwnerAdapter: QueryAdapter = { descriptor: forestRecreationOwnerDescriptor, allowedParameters: {}, read: (_parameters: Readonly<Record<string, Scalar>>, signal?: AbortSignal) => read(signal) };
