import { withLoading } from "../lib/loadingRegistry";
import { boundedAccess, DEFAULT_VALUE_SEMANTICS, type DatasetDescriptor, type DatasetField, type Scalar, type SourceReceipt } from "./dataContracts";
import { parseLineGeometry } from "./lineGeometry";
import { createLineDatasetAdapter, type AdapterSnapshot } from "./queryAdapters";

type Bbox = readonly [number, number, number, number];
type Shard = { path: string; sha256: string; bytes: number; encoding: "gzip"; uncompressedSha256: string; uncompressedBytes: number; featureCount: number; bbox: Bbox };
type Manifest = { schemaVersion: "pulse-line-partitions/1"; source: { sha256: string; bytes: number; featureCount: number; reference: string }; shards: Shard[] };
export type HikingTrailFetch = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;

const SOURCE_SHA256 = "0c0263b33f7561bc0b06432f6fdd1b5494c2b2978169a16f53616e68305aea9c";
const MANIFEST_SHA256 = "e1506ec71627c3eff5c5ad7a2d4c8e92af0a5d617b83e4cad97043bba0badbb4";
const SOURCE_REFERENCE = `/research/hiking-trails/source-identity/sha256-${SOURCE_SHA256}`;
const PREFIX = "/__local-research-owner-only/hiking-trails/", MANIFEST_URL = `${PREFIX}manifest.json`;
const MAX_BYTES = 8 * 1024 * 1024, MAX_ROWS = 20_000;
const fields: readonly DatasetField[] = [
  { name: "record_id", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "source", type: "string", nullable: false, nullMeaning: null, unit: null },
  { name: "source_license", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "source_geometry_type", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "source_id", type: "string", nullable: false, nullMeaning: null, unit: null },
  { name: "name", type: "string", nullable: true, nullMeaning: "來源未命名步道；不代表沒有步道。", unit: null }, { name: "region", type: "string", nullable: true, nullMeaning: "OSM 等來源未提供 region；且此欄跨來源語意不一致。", unit: null },
  { name: "main_sys", type: "string", nullable: true, nullMeaning: "來源未提供主管或步道系統。", unit: null }, { name: "url", type: "string", nullable: false, nullMeaning: null, unit: null },
  { name: "is_dup_of_A", type: "boolean", nullable: false, nullMeaning: null, unit: null }, { name: "overlap_ratio_A", type: "string", nullable: true, nullMeaning: "A_forest 無此去重比例；null 不是零重疊。", unit: null },
  { name: "in_national_park", type: "string", nullable: true, nullMeaning: "未命中國家公園 join 或來源未標示；不代表不在其他保護地。", unit: null }, { name: "geometry", type: "json", nullable: false, nullMeaning: null, unit: null },
];
export const hikingTrailsOwnerDescriptor: DatasetDescriptor = {
  schemaVersion: "pulse-dataset/0.1", datasetId: "tw-hiking-trails-6source-20260608-owner-only", label: "全臺步道線形（6 源 2026-06-08 owner-only）",
  description: "6 源合併的 7,339 條固定步道路徑。每次須提供 bbox，僅讀取可能相交的 immutable local shards，並以完整 LineString/MultiLineString 判斷相交。線形不代表導航、入口、目前開放、路況、安全、步行距離、可達性或服務範圍。",
  layerRefs: ["hikingTrails"], kind: "line", recordGrain: "feature", primaryKey: ["source", "source_id"], fields,
  geometry: { type: "MultiLineString", crs: "EPSG:4326", role: "actual", precision: "保留原始 WGS84 路徑的完整頂點；7,324 個 LineString 以一段 MultiLineString 表示、15 個原 MultiLineString 保留多段，source_geometry_type 保留原型。未以點、bbox 或顯示 PMTiles 代替。", spatialAnalysisEligible: true },
  timeFields: [], coverage: "固定 2026-06-08 合併快照：A_forest 345、B_osm 6,563、C_np_sheipa 93、C_np_kinmen 20、D_taipei_grand 11、D_newtaipei 307，共 7,339 條。B_osm 佔 89.4% 且 region 缺 6,563、name 缺 1,107；未命中 bbox 只表示這一固定 6 源快照沒有相交線。",
  license: "A/C/D 為 OGDL-Taiwan-1.0；B_osm 為 ODbL-1.0，須標示 © OpenStreetMap contributors。每列 source 與 source_license 均保留。",
  valueSemantics: { ...DEFAULT_VALUE_SEMANTICS, missing: "name、region、main_sys、in_national_park 與 overlap_ratio_A 的 null 是來源或處理欄位缺值，不能改為空字串、零或否定結論。", stale: "static 2026-06-08 合併快照；OSM Overpass 與新北上游可變動，不能代表目前完整性、開放、封閉、施工或現場狀態。" },
  versions: [{ versionId: `processed-sha256:${SOURCE_SHA256}`, observedAt: null, availableAt: "2026-06-08", checksumSha256: SOURCE_SHA256, mutable: false }],
  source: { publisher: "農業部林業及自然保育署、OpenStreetMap contributors、雪霸與金門國家公園、臺北市政府、新北市政府", reference: SOURCE_REFERENCE, lineage: "6 sources -> analytics processed hiking_trails.geojson -> byte-identical Mini public/forestry/hiking_trails.geojson SHA-256 0c0263…aea9c -> immutable owner-only spatial shards. A_forest is authoritative in a 50m duplicate screen; B/C/D overlap each other may remain." },
  access: boundedAccess({ mode: "owner_only", method: "local_asset", fields: fields.map(field => field.name), filters: ["source", "source_license", "source_id", "name", "region", "main_sys", "is_dup_of_A", "in_national_park"], supportsBbox: true, maxRowsPerQuery: 100, maxScanRows: MAX_ROWS, maxSourceBytes: MAX_BYTES, maxResponseBytes: 1024 * 1024, timeoutMs: 15_000 }),
  supportedOperations: ["query_records", "line_intersects"], adapterId: "hiking-trails-owner-line-partitions-v1",
};
function fail(code: string): never { throw new Error(code); }
function hashLike(value: unknown): value is string { return typeof value === "string" && /^[a-f0-9]{64}$/.test(value); }
function bbox(value: unknown): value is Bbox { return Array.isArray(value) && value.length === 4 && value.every(part => typeof part === "number" && Number.isFinite(part)) && value[0]! >= -180 && value[1]! >= -90 && value[2]! <= 180 && value[3]! <= 90 && value[0]! <= value[2]! && value[1]! <= value[3]!; }
function intersects(left: Bbox, right: Bbox): boolean { return left[0] <= right[2] && left[2] >= right[0] && left[1] <= right[3] && left[3] >= right[1]; }
async function digest(bytes: Uint8Array): Promise<string> { const value = await crypto.subtle.digest("SHA-256", bytes); return [...new Uint8Array(value)].map(part => part.toString(16).padStart(2, "0")).join(""); }
async function bytes(response: Response): Promise<Uint8Array> { const declared = Number(response.headers.get("content-length")); if (Number.isFinite(declared) && declared > MAX_BYTES) fail("HIKING_TRAILS_ASSET_TOO_LARGE"); const value = new Uint8Array(await response.arrayBuffer()); if (value.byteLength > MAX_BYTES) fail("HIKING_TRAILS_ASSET_TOO_LARGE"); return value; }
function parse(value: Uint8Array): unknown { try { return JSON.parse(new TextDecoder().decode(value)); } catch { return fail("HIKING_TRAILS_ASSET_INVALID"); } }
async function gunzip(value: Uint8Array, shard: Shard): Promise<Uint8Array> { if (value.byteLength === shard.uncompressedBytes && await digest(value) === shard.uncompressedSha256) return value; if (await digest(value) !== shard.sha256 || typeof DecompressionStream === "undefined") fail("HIKING_TRAILS_SHARD_SHA_MISMATCH"); const output = new Uint8Array(await new Response(new Blob([value]).stream().pipeThrough(new DecompressionStream("gzip"))).arrayBuffer()); if (output.byteLength !== shard.uncompressedBytes || await digest(output) !== shard.uncompressedSha256) fail("HIKING_TRAILS_SHARD_DECODE_MISMATCH"); return output; }
function manifest(value: unknown): Manifest { const candidate = value as Partial<Manifest>; if (!candidate || candidate.schemaVersion !== "pulse-line-partitions/1" || !candidate.source || candidate.source.sha256 !== SOURCE_SHA256 || candidate.source.bytes !== 20_659_963 || candidate.source.featureCount !== 7339 || candidate.source.reference !== SOURCE_REFERENCE || !Array.isArray(candidate.shards) || !candidate.shards.length || candidate.shards.length > 1024) fail("HIKING_TRAILS_MANIFEST_INVALID"); const paths = new Set<string>(); for (const shard of candidate.shards) if (!shard || !hashLike(shard.sha256) || !hashLike(shard.uncompressedSha256) || shard.path !== `${shard.sha256}.geojson.gz` || shard.encoding !== "gzip" || !Number.isSafeInteger(shard.bytes) || !Number.isSafeInteger(shard.uncompressedBytes) || !Number.isSafeInteger(shard.featureCount) || shard.featureCount < 1 || !bbox(shard.bbox) || paths.has(shard.path)) fail("HIKING_TRAILS_MANIFEST_INVALID"); else paths.add(shard.path); if (candidate.shards.reduce((total, shard) => total + shard.featureCount, 0) !== 7339) fail("HIKING_TRAILS_MANIFEST_INVALID"); return candidate as Manifest; }
function rows(value: unknown, shard: Shard, ordinals: Set<number>): Record<string, unknown>[] { const collection = value as { type?: unknown; features?: unknown[] }; if (collection?.type !== "FeatureCollection" || !Array.isArray(collection.features) || collection.features.length !== shard.featureCount) fail("HIKING_TRAILS_SHARD_INVALID"); return collection.features.map(raw => { const item = raw as { type?: unknown; sourceOrdinal?: unknown; properties?: Record<string, unknown>; geometry?: unknown }, p = item.properties, ordinal = typeof item.sourceOrdinal === "number" ? item.sourceOrdinal : NaN; if (item?.type !== "Feature" || !Number.isSafeInteger(ordinal) || ordinal < 0 || ordinal >= 7339 || ordinals.has(ordinal) || !p || typeof p.source !== "string" || typeof p.source_id !== "string" || typeof p.source_license !== "string" || !["LineString", "MultiLineString"].includes(String(p.source_geometry_type)) || !(p.name === null || typeof p.name === "string") || !(p.region === null || typeof p.region === "string") || !(p.main_sys === null || typeof p.main_sys === "string") || typeof p.url !== "string" || typeof p.is_dup_of_A !== "boolean" || !(p.overlap_ratio_A === null || typeof p.overlap_ratio_A === "string") || !(p.in_national_park === null || typeof p.in_national_park === "string")) fail("HIKING_TRAILS_ROW_INVALID"); const geometry = parseLineGeometry(item.geometry); if (geometry.type !== "MultiLineString") fail("HIKING_TRAILS_GEOMETRY_INVALID"); ordinals.add(ordinal); return { record_id: `${SOURCE_SHA256}-${ordinal}`, ...p, geometry }; }); }
export function clearHikingTrailsOwnerCache(): void { cache.clear(); }
const cache = new Map<string, Uint8Array>();
async function fetchImmutable(fetcher: HikingTrailFetch, url: string, expected: string, signal?: AbortSignal, decoded?: { sha256: string; bytes: number }): Promise<{ value: Uint8Array; cacheHit: boolean }> { const cached = cache.get(url); if (cached) return { value: cached, cacheHit: true }; const response = await fetcher(url, { credentials: "same-origin", redirect: "error", signal: signal ?? AbortSignal.timeout(15_000) }); if (!response.ok || response.headers.get("content-type")?.includes("text/html")) fail("HIKING_TRAILS_ASSET_UNAVAILABLE"); const value = await bytes(response), sha256 = await digest(value); if (sha256 !== expected && !(decoded && value.byteLength === decoded.bytes && sha256 === decoded.sha256)) fail("HIKING_TRAILS_ASSET_SHA_MISMATCH"); cache.set(url, value); return { value, cacheHit: false }; }
async function read(_parameters: Readonly<Record<string, Scalar>>, signal: AbortSignal | undefined, context: { bbox?: Bbox } | undefined, fetcher: HikingTrailFetch): Promise<AdapterSnapshot> { if (!context?.bbox) fail("BBOX_REQUIRED"); return withLoading("research:hiking-trails-owner", "讀取全臺步道路徑", (async () => { const manifestAsset = await fetchImmutable(fetcher, MANIFEST_URL, MANIFEST_SHA256, signal); const data = manifest(parse(manifestAsset.value)), selected = data.shards.filter(shard => intersects(shard.bbox, context.bbox!)); if (selected.reduce((total, shard) => total + shard.uncompressedBytes, manifestAsset.value.byteLength) > MAX_BYTES || selected.reduce((total, shard) => total + shard.featureCount, 0) > MAX_ROWS) fail("HIKING_TRAILS_QUERY_TOO_BROAD"); const ordinals = new Set<number>(); let bytesScanned = manifestAsset.value.byteLength, downloadedBytes = manifestAsset.cacheHit ? 0 : manifestAsset.value.byteLength, requests = manifestAsset.cacheHit ? 0 : 1; const result: Record<string, unknown>[] = []; for (const shard of selected) { const asset = await fetchImmutable(fetcher, `${PREFIX}${shard.path}`, shard.sha256, signal, { sha256: shard.uncompressedSha256, bytes: shard.uncompressedBytes }); const decoded = await gunzip(asset.value, shard); bytesScanned += decoded.byteLength; if (!asset.cacheHit) { downloadedBytes += asset.value.byteLength; requests++; } result.push(...rows(parse(decoded), shard, ordinals)); } const source: SourceReceipt = { sourceId: hikingTrailsOwnerDescriptor.datasetId, version: `sha256:${SOURCE_SHA256}`, checksumSha256: SOURCE_SHA256, reference: SOURCE_REFERENCE, acquiredAt: new Date().toISOString() }; return { rows: result, source, coverage: hikingTrailsOwnerDescriptor.coverage, freshness: "stale", exclusions: {}, rowsScanned: result.length, bytesScanned, downloadedBytes, requests, cacheHit: manifestAsset.cacheHit && selected.every(shard => cache.has(`${PREFIX}${shard.path}`)) }; })()); }
export function createHikingTrailsOwnerAdapter(fetcher: HikingTrailFetch = fetch) { return createLineDatasetAdapter(hikingTrailsOwnerDescriptor, (parameters, signal, context) => read(parameters, signal, context, fetcher)); }
export const hikingTrailsOwnerAdapter = createHikingTrailsOwnerAdapter();
