import { boundedAccess, DEFAULT_VALUE_SEMANTICS, type DatasetDescriptor, type DatasetField, type Scalar, type SourceReceipt } from "./dataContracts";
import { loadPointDataset } from "./pointDatasetAdapter";
import { createReferencePointDatasetAdapter, type AdapterSnapshot } from "./queryAdapters";

type Family = { datasetId: string; layer: "lpgSubpackaging" | "lpgRetailers"; label: string; url: string; sha256: string; rows: number; category: "subpackaging" | "retailers"; coverage: string };
const sourceSha = "a22841339ec56843b14effec9564461228c42e9c58a2df48659fa34c83a26afa";
const fields: readonly DatasetField[] = [
  { name: "record_id", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "entity_id", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "name", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "category", type: "string", nullable: false, nullMeaning: null, unit: null },
  ...(["is_subpackaging", "is_retailer", "is_cstation", "is_dealer"] as const).map(name => ({ name, type: "boolean" as const, nullable: false, nullMeaning: null, unit: null })),
  { name: "source", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "source_tier", type: "number", nullable: false, nullMeaning: null, unit: "trust tier" }, { name: "coord_source", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "fetched_at", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "confidence", type: "number", nullable: true, nullMeaning: "Pipeline confidence is absent; it does not prove location accuracy.", unit: null }, { name: "license", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "geometry", type: "json", nullable: false, nullMeaning: null, unit: null },
];
const subpackagingFamily: Family = { datasetId: "tw-lpg-subpackaging-owner-20260620", layer: "lpgSubpackaging", label: "LPG 分裝場（owner-only 2026-06-20）", url: "/__local-research-owner-only/lpg/lpg-subpackaging-owner-20260620.geojson", sha256: "f7a4af144803aa787a47f9df9b66cdef413f4a7e4638e86338ccb8062620f7ba", rows: 107, category: "subpackaging", coverage: "13 來源合流後，facility_kinds 包含 subpackaging 的 107 個 canonical Point。它可同時帶有零售、經銷或 facility_mixed 標籤；不等於全國所有 LPG 儲槽、驗瓶或分裝設施。" };
const retailersFamily: Family = { datasetId: "tw-lpg-retailers-owner-20260620", layer: "lpgRetailers", label: "LPG 零售／加氣／經銷（owner-only 2026-06-20）", url: "/__local-research-owner-only/lpg/lpg-retailers-owner-20260620.geojson", sha256: "dd13ad470858c06d6d449b683ac2ac4d596c9c105434e4ed7106be50308235ee", rows: 567, category: "retailers", coverage: "13 來源合流後，facility_kinds 包含 retailer、cstation 或 dealer 的 567 個 canonical Point。facility_mixed-only 的 624 個實體未納入，故不可視為全國 LPG 設施完整母體。" };

function descriptor(family: Family): DatasetDescriptor { return { schemaVersion: "pulse-dataset/0.1", datasetId: family.datasetId, label: family.label, description: "固定合流快照，以本機 owner-only safe-field sidecar 做 bbox 與屬性查詢。來源授權資料相互矛盾，不能公開或作最近設施、可達性、營運與服務範圍解釋。", layerRefs: [family.layer], kind: "point", recordGrain: "place", primaryKey: ["record_id"], fields, geometry: { type: "Point", crs: "EPSG:4326", role: "proxy", precision: "Canonical point is a deduplicated reference coordinate (150m fuzzy dedup tolerance). It is not a storefront/entrance, confirmed operating facility, nearest LPG service, route distance, safety status, capacity, coverage, or accessibility measurement.", spatialAnalysisEligible: false }, timeFields: [], coverage: `${family.coverage} 來源 1,292 列中 entity_id 僅 1,201 個不同值；82 個值重複、額外 91 列，因此查詢以側錄列號 record_id 作唯一鍵，不把 source entity_id 當唯一實體。`, license: "RIGHTS_HOLD: catalog describes the 13 sources as mixed OGDL and CC BY, while processed rows say OGDL-Taiwan-1.0. Source-by-source license receipts and coordinate redistribution terms need reconciliation; owner-only only.", valueSemantics: { ...DEFAULT_VALUE_SEMANTICS, missing: "No Point in a bbox does not mean no LPG service, supplier, cylinder exchange, storage or operating facility.", stale: "2026-06-20 fixed snapshot does not establish current operation, stock, delivery, safety, permits or opening." }, versions: [{ versionId: `20260620-sidecar-${family.sha256}`, observedAt: null, availableAt: "2026-06-20T00:00:00+08:00", checksumSha256: family.sha256, mutable: false }], source: { publisher: "經濟部能源署、中油與縣市 data.gov mirror（13 source trust-chain merge）", reference: family.url, lineage: `13 sources / 1,743 input rows -> 1,292 canonical rows (150m poi_geocoded fuzzy dedup; 1,201 distinct entity_id values) processed source SHA-256 ${sourceSha} -> ${family.category} safe-field owner-only subset SHA-256 ${family.sha256}. _provenance, aliases, source_url and address/phone/name_raw are not exposed.` }, access: boundedAccess({ mode: "owner_only", method: "local_asset", fields: fields.map(field => field.name), filters: fields.filter(field => !["record_id", "geometry"].includes(field.name)).map(field => field.name), supportsBbox: true, maxRowsPerQuery: 100, maxScanRows: family.rows, maxSourceBytes: 512 * 1024 }), supportedOperations: ["query_records", "aggregate"], adapterId: `${family.layer}-owner-reference-v1` }; }
async function read(family: Family, descriptor: DatasetDescriptor, _parameters: Readonly<Record<string, Scalar>>, signal?: AbortSignal): Promise<AdapterSnapshot> { const snapshot = await loadPointDataset({ datasetId: descriptor.datasetId, url: family.url, idField: "entity_id", safeFields: fields.map(field => field.name).filter(name => !["record_id", "geometry"].includes(name)) }, { signal }); if (snapshot.checksumSha256 !== family.sha256 || snapshot.rows.length !== family.rows || Object.values(snapshot.exclusions).some(Boolean)) throw new Error("LPG_OWNER_SIDECAR_MISMATCH"); const source: SourceReceipt = { sourceId: descriptor.datasetId, version: `sha256:${family.sha256}`, acquiredAt: snapshot.acquiredAt, checksumSha256: family.sha256, reference: family.url }; return { rows: snapshot.rows, source, coverage: descriptor.coverage, freshness: "stale", exclusions: snapshot.exclusions, rowsScanned: snapshot.rows.length, bytesScanned: snapshot.bytes, downloadedBytes: snapshot.downloadedBytes, requests: snapshot.requests, cacheHit: snapshot.cacheHit }; }
export const lpgSubpackagingOwnerDescriptor = descriptor(subpackagingFamily);
export const lpgRetailersOwnerDescriptor = descriptor(retailersFamily);
export const lpgSubpackagingOwnerAdapter = createReferencePointDatasetAdapter(lpgSubpackagingOwnerDescriptor, (parameters, signal) => read(subpackagingFamily, lpgSubpackagingOwnerDescriptor, parameters, signal));
export const lpgRetailersOwnerAdapter = createReferencePointDatasetAdapter(lpgRetailersOwnerDescriptor, (parameters, signal) => read(retailersFamily, lpgRetailersOwnerDescriptor, parameters, signal));
