import { boundedAccess, DEFAULT_VALUE_SEMANTICS, type DatasetDescriptor, type DatasetField, type Scalar, type SourceReceipt } from "./dataContracts";
import { loadPointDataset } from "./pointDatasetAdapter";
import { createReferencePointDatasetAdapter, type AdapterSnapshot } from "./queryAdapters";

type Family = { datasetId: string; url: string; sha256: string; count: number; fields: readonly DatasetField[]; label: string; coverage: string; license: string; source: DatasetDescriptor["source"]; exclusions: Readonly<Record<string, number>>; layer: string };
const field = (name: string, type: DatasetField["type"], nullable = false): DatasetField => ({ name, type, nullable, nullMeaning: nullable ? "Source explicitly has no value." : null, unit: null });
const huts: Family = { datasetId: "tw-mountain-huts-20260801-owner-only", url: "/__local-research-owner-only/mountain-points/mountain-huts-owner-20260801.geojson", sha256: "ae47329221a44a2931fbe53c73d1cb79af8e72eee1c530e3bbbc47e4dcecd77b", count: 136, layer: "mountainHuts", fields: [field("record_id", "string"), field("name", "string", true), field("facility_type", "string"), field("source", "string"), field("source_tier", "number"), field("coord_source", "string"), field("in_yushan_official", "boolean"), field("fetched_at", "string"), field("geometry", "json")], label: "山屋與高山營地（20260801 owner-only）", coverage: "136 個合併實體：玉山官方 30、OSM-only 106；不是全台完整名冊，雪霸、太魯閣、林業署缺少官方開放點位。空 name 12 筆是保留的無名 OSM 棚屋。", license: "玉山來源 OGDL-Taiwan-1.0；OSM 來源 ODbL-1.0，使用時須標示 © OpenStreetMap contributors。", source: { publisher: "玉山國家公園管理處（data.gov.tw:7449）與 OpenStreetMap contributors", reference: "/research/mountain-huts/source-identity/sha256-5e9f4a1017089dd02540720f1da34b191048e1638dcacf0e29f5aec77f6212e4", lineage: "玉山 114 年修 SHP ZIP SHA-256 d852…75b3（30）+ OSM Overpass raw SHA-256 ad3e…27e1（126 input）-> trust-chain 136 Point processed SHA-256 5e9f…12e4 -> safe-field owner-only sidecar。" }, exclusions: { unnamed_osm_shelters: 12, osm_only_entities: 106 } };
const rescues: Family = { datasetId: "tw-mountain-rescue-incidents-2019-2024-owner-only", url: "/__local-research-owner-only/mountain-points/mountain-rescue-incidents-owner-20260801.geojson", sha256: "da0d3a1ab4e08a67bb819e795ebefabd355aa0ba78b776d72d937d7b9163c058", count: 2465, layer: "mountainRescueIncidents", fields: [field("record_id", "string"), field("year", "number"), field("city", "string"), field("mountain_area", "string", true), field("cause", "string", true), field("over_48hr", "string", true), field("deaths", "number", true), field("rescued", "number", true), field("missing", "number", true), field("source_dataset", "string"), field("geometry", "json")], label: "山域意外救援案件（2019-2024 owner-only）", coverage: "消防署 2019-2024 固定歷史快照 2,465 Point；原始跨源重複已去重，5 筆壞座標已排除。不是即時事故、風險預測、封閉或救援資源狀態。", license: "OGDL-Taiwan-1.0；sidecar 已排除個案 ID、精確報案/搜救/結案時間、路線與管理或醫療備註。", source: { publisher: "內政部消防署（data.gov.tw:170544）", reference: "/research/mountain-rescue-incidents/source-identity/sha256-b1301673d2575e18acc59e9204dfffbf2810fc13c2a755dc2003ef02c4dba2dd", lineage: "NFA 170544 yearly CSV plus byte-identical 147055 historic CSV -> full-field dedupe -> 5 bad coordinates excluded -> 2,465 Point processed SHA-256 b130…a2dd -> de-identified safe-field owner-only sidecar。" }, exclusions: { invalid_or_outside_taiwan_coordinates: 5, duplicate_source_rows: 1012, precise_times_withheld: 2465, source_case_ids_withheld: 2465 } };
function descriptor(family: Family): DatasetDescriptor { return { schemaVersion: "pulse-dataset/0.1", datasetId: family.datasetId, label: family.label, description: "bbox and attribute reads only through a local owner-only safe-field sidecar.", layerRefs: [family.layer], kind: "point", recordGrain: family.layer === "mountainHuts" ? "place" : "event", primaryKey: ["record_id"], fields: family.fields, geometry: { type: "Point", crs: "EPSG:4326", role: "proxy", precision: "Reference Point only; it cannot establish nearest shelter, trail access, route condition, current opening, current rescue incident, terrain safety, walking, transit, or emergency response access.", spatialAnalysisEligible: false }, timeFields: [], coverage: family.coverage, license: family.license, valueSemantics: { ...DEFAULT_VALUE_SEMANTICS, missing: "No Point in a bbox is not evidence of no hut, no rescue incident, no risk, or no access.", stale: "Fixed 2026-08-01 release does not establish current conditions or availability." }, versions: [{ versionId: `sha256:${family.sha256}`, observedAt: null, availableAt: "2026-08-01", checksumSha256: family.sha256, mutable: false }], source: family.source, access: boundedAccess({ mode: "owner_only", method: "local_asset", fields: family.fields.map(item => item.name), filters: family.fields.filter(item => !["record_id", "geometry"].includes(item.name)).map(item => item.name), supportsBbox: true, maxRowsPerQuery: 100, maxScanRows: family.count, maxSourceBytes: 1024 * 1024 }), supportedOperations: ["query_records", "aggregate"], adapterId: `${family.layer}-owner-reference-v1` }; }
export const mountainHutsOwnerDescriptor = descriptor(huts); export const mountainRescueIncidentsOwnerDescriptor = descriptor(rescues);
async function read(family: Family, value: DatasetDescriptor, _parameters: Readonly<Record<string, Scalar>>, signal?: AbortSignal, context?: { bbox?: readonly [number, number, number, number] }): Promise<AdapterSnapshot> { if (!context?.bbox) throw new Error("BBOX_REQUIRED"); const snapshot = await loadPointDataset({ datasetId: family.datasetId, url: family.url, idField: "record_id", safeFields: family.fields.map(item => item.name).filter(name => !["record_id", "geometry"].includes(name)) }, { signal }); if (snapshot.checksumSha256 !== family.sha256 || snapshot.rows.length !== family.count || snapshot.exclusions.missing_geometry || snapshot.exclusions.non_point_geometry || snapshot.exclusions.invalid_geometry) throw new Error("MOUNTAIN_OWNER_SOURCE_SEMANTICS_MISMATCH"); const source: SourceReceipt = { sourceId: family.datasetId, version: `sha256:${family.sha256}`, acquiredAt: snapshot.acquiredAt, checksumSha256: family.sha256, reference: family.url }; return { rows: snapshot.rows, source, coverage: value.coverage, freshness: "stale", exclusions: { ...family.exclusions, ...snapshot.exclusions }, rowsScanned: snapshot.rows.length, bytesScanned: snapshot.bytes, downloadedBytes: snapshot.downloadedBytes, requests: snapshot.requests, cacheHit: snapshot.cacheHit }; }
export const mountainHutsOwnerAdapter = createReferencePointDatasetAdapter(mountainHutsOwnerDescriptor, (p, s, c) => read(huts, mountainHutsOwnerDescriptor, p, s, c));
export const mountainRescueIncidentsOwnerAdapter = createReferencePointDatasetAdapter(mountainRescueIncidentsOwnerDescriptor, (p, s, c) => read(rescues, mountainRescueIncidentsOwnerDescriptor, p, s, c));
