import { withLoading } from "../lib/loadingRegistry";
import { boundedAccess, DEFAULT_VALUE_SEMANTICS, type DatasetDescriptor, type DatasetField, type Scalar, type SourceReceipt } from "./dataContracts";
import { createLineDatasetAdapter, createPointDatasetAdapter, type AdapterSnapshot } from "./queryAdapters";
import type { QueryAdapter, QueryReadContext } from "./queryExecutor";

const LINE_URL = "/__local-research-owner-only/osm-power-network/osm_power_lines_20260615.geojson";
const TOWER_URL = "/__local-research-owner-only/osm-power-network/osm_power_towers_20260615.geojson";
const LINE_SHA256 = "538411022f39cb51d3e928c36a33fafde82aec9a8d8cdb8554ee75e9d0678267";
const TOWER_SHA256 = "1e7813105955e53f8cdc98dde900b0b7e8f537d3121645bb1bfef1c6af70ff49";
const LINE_COUNT = 2_305; const TOWER_COUNT = 26_589; const MAX_BYTES = 8 * 1024 * 1024;
const optional = (name: string, nullMeaning: string): DatasetField => ({ name, type: "string", nullable: true, nullMeaning, unit: null });
const lineFields: readonly DatasetField[] = [
  { name: "record_id", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "osm_id", type: "number", nullable: false, nullMeaning: null, unit: null },
  { name: "line_type", type: "string", nullable: false, nullMeaning: null, unit: null }, optional("voltage", "OSM 未標示電壓；不是零伏、無電或停用。"), optional("circuits", "OSM 未標示迴路數；不是零迴路。"), optional("cables", "OSM 未標示電纜數；不是零。"), optional("operator", "OSM 未標示營運者；不能推論無管理單位。"), optional("frequency", "OSM 未標示頻率；不是無交流電。"), optional("location", "OSM 未標示位置型態；不能推論架空或地下。"), { name: "geometry", type: "json", nullable: false, nullMeaning: null, unit: null },
];
const towerFields: readonly DatasetField[] = [
  { name: "record_id", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "osm_id", type: "number", nullable: false, nullMeaning: null, unit: null }, optional("voltage", "OSM 未標示電壓；不是零伏、無電或停用。"), optional("operator", "OSM 未標示營運者；不能推論無管理單位。"), optional("material", "OSM 未標示材質；不是無材質。"), optional("design", "OSM 未標示塔型；不是無塔型。"), optional("ref", "OSM 未標示編號；不是沒有編號。"), { name: "geometry", type: "json", nullable: false, nullMeaning: null, unit: null },
];
const sourceText = "OpenStreetMap contributors，Overpass 固定快照";
const common = { ...DEFAULT_VALUE_SEMANTICS, missing: "bbox 無結果只表示此固定 OSM 快照未有符合的已繪製要素；不能推論沒有輸電設施、供電、停電、可達性或營運狀態。", null: "null 是該 OSM tag 未標示；不得替換為零、否或目前狀態。", stale: "2026-06-15 固定 OSM 快照不代表目前線路、鐵塔、電壓、所有權、通電、施工、故障或現場安全狀態。" };
export const osmPowerLinesOwnerDescriptor: DatasetDescriptor = {
  schemaVersion: "pulse-dataset/0.1", datasetId: "tw-osm-power-lines-owner-20260615", label: "OSM 高壓輸電線（owner-only 2026-06-15）", description: "2,305 條 OSM `power=line|minor_line|cable` Way 的固定完整 LineString 快照。線幾何只表示社群繪製路徑，不能作為走線權屬、地下位置、精確安全距離、容量或供電狀態。", layerRefs: ["osmPowerLines"], kind: "line", recordGrain: "feature", primaryKey: ["record_id"], fields: lineFields,
  geometry: { type: "LineString", crs: "EPSG:4326", role: "actual", precision: "Overpass Way geometry 的每個 WGS84 頂點依原始順序完整保留，未取中心點或簡化；它仍是 OSM 繪製精度，不能推論法定走廊或地面實測位置。", spatialAnalysisEligible: true }, timeFields: [], coverage: "2026-06-15 固定快照共 2,305 LineString；bbox 為必要條件，reader 仍以完整 1.82 MB 固定 sidecar 掃描，最多回傳 5 筆。未標記、未繪製、範圍外或後續變更均不在此快照。", license: "ODbL 1.0；使用與衍生資料須保留 © OpenStreetMap contributors，並遵守 ODbL 的署名與分享相同條件。", valueSemantics: common,
  versions: [{ versionId: `20260615-geojson-sha256:${LINE_SHA256}`, observedAt: null, availableAt: "2026-06-15", checksumSha256: LINE_SHA256, mutable: false }], source: { publisher: sourceText, reference: LINE_URL, lineage: `Overpass raw osm_power_lines_20260615.json SHA-256 c6cc21e8607cac1cf02a69a5b6ba764703d43aad174e01ab671eb78950f49217 (2,305 Way) -> processed immutable GeoJSON SHA-256 ${LINE_SHA256} (2,305 LineString, osm_id one-to-one, all Way geometry coordinates and selected tag values verified) -> byte-identical localhost owner-only sidecar.` },
  access: boundedAccess({ mode: "owner_only", method: "local_asset", fields: lineFields.map(x => x.name), filters: ["osm_id", "line_type", "voltage", "circuits", "cables", "operator", "frequency", "location"], supportsBbox: true, maxRowsPerQuery: 5, maxScanRows: LINE_COUNT, maxSourceBytes: MAX_BYTES, timeoutMs: 15_000 }), supportedOperations: ["query_records", "line_intersects", "aggregate"], adapterId: "osm-power-lines-owner-20260615-v1",
};
export const osmPowerTowersOwnerDescriptor: DatasetDescriptor = {
  schemaVersion: "pulse-dataset/0.1", datasetId: "tw-osm-power-towers-owner-20260615", label: "OSM 高壓鐵塔（owner-only 2026-06-15）", description: "26,589 個 OSM `power=tower` Node 的固定 Point 快照。點位是 OSM 社群繪製位置，不能作為塔基界址、入口、最近塔、可達性、通電或安全狀態。", layerRefs: ["osmPowerTowers"], kind: "point", recordGrain: "place", primaryKey: ["record_id"], fields: towerFields,
  geometry: { type: "Point", crs: "EPSG:4326", role: "actual", precision: "Overpass Node 的 WGS84 經緯度完整保留；沒有位移或中心化，但座標品質取決於 OSM 繪製，並非工程或安全測量。", spatialAnalysisEligible: true }, timeFields: [], coverage: "2026-06-15 固定快照共 26,589 Point；bbox 為必要條件，reader 最多掃描 26,589 筆並回傳 100 筆。bbox 外、未標記、未繪製或後續變更不表示不存在。", license: "ODbL 1.0；使用與衍生資料須保留 © OpenStreetMap contributors，並遵守 ODbL 的署名與分享相同條件。", valueSemantics: common,
  versions: [{ versionId: `20260615-geojson-sha256:${TOWER_SHA256}`, observedAt: null, availableAt: "2026-06-15", checksumSha256: TOWER_SHA256, mutable: false }], source: { publisher: sourceText, reference: TOWER_URL, lineage: `Overpass raw osm_power_towers_20260615.json SHA-256 4dc1f3f22f63f1d1d9030b66a941d3e72a0037e28d1592ac1d75853fa4bbd545 (26,589 Node) -> processed immutable GeoJSON SHA-256 ${TOWER_SHA256} (26,589 Point, osm_id one-to-one, all node coordinates and selected tag values verified) -> byte-identical localhost owner-only sidecar.` },
  access: boundedAccess({ mode: "owner_only", method: "local_asset", fields: towerFields.map(x => x.name), filters: ["osm_id", "voltage", "operator", "material", "design", "ref"], supportsBbox: true, maxRowsPerQuery: 100, maxScanRows: TOWER_COUNT, maxSourceBytes: MAX_BYTES, timeoutMs: 15_000 }), supportedOperations: ["query_records", "aggregate"], adapterId: "osm-power-towers-owner-20260615-v1",
};
type Fetcher = (input: RequestInfo | URL, init?: RequestInit) => Promise<Response>;
type Snapshot = { rows: readonly Record<string, unknown>[]; bytes: number };
const cache = new Map<string, Snapshot>();
function fail(code: string): never { throw new Error(code); }
function validPoint(c: unknown): c is readonly [number, number] { return Array.isArray(c) && c.length === 2 && c.every(x => typeof x === "number" && Number.isFinite(x)) && Math.abs(c[0] as number) <= 180 && Math.abs(c[1] as number) <= 90; }
async function bytes(response: Response): Promise<Uint8Array> { const length = Number(response.headers.get("content-length")); if (Number.isFinite(length) && length > MAX_BYTES) fail("OSM_POWER_SOURCE_TOO_LARGE"); const result = new Uint8Array(await response.arrayBuffer()); if (result.byteLength > MAX_BYTES) fail("OSM_POWER_SOURCE_TOO_LARGE"); return result; }
async function digest(value: Uint8Array): Promise<string> { const hash = await crypto.subtle.digest("SHA-256", value); return [...new Uint8Array(hash)].map(x => x.toString(16).padStart(2, "0")).join(""); }
function parse(kind: "line" | "tower", value: Uint8Array): Snapshot { let raw: unknown; try { raw = JSON.parse(new TextDecoder().decode(value)); } catch { fail("INVALID_OSM_POWER_SNAPSHOT"); } const count = kind === "line" ? LINE_COUNT : TOWER_COUNT; const fields = kind === "line" ? ["osm_id", "line_type", "voltage", "circuits", "cables", "operator", "frequency", "location"] : ["osm_id", "voltage", "operator", "material", "design", "ref"]; if (!raw || typeof raw !== "object" || (raw as { type?: unknown }).type !== "FeatureCollection" || !Array.isArray((raw as { features?: unknown }).features) || (raw as { features: unknown[] }).features.length !== count) fail("INVALID_OSM_POWER_SNAPSHOT"); const ids = new Set<number>(); const rows = (raw as { features: unknown[] }).features.map((feature, index) => { const f = feature as { type?: unknown; geometry?: { type?: unknown; coordinates?: unknown }; properties?: Record<string, unknown> }; const p = f?.properties; const geometry = f?.geometry; const osmId = p?.osm_id; if (f?.type !== "Feature" || !p || !geometry || !Number.isSafeInteger(osmId) || fields.some(name => !(name in p)) || Object.values(p).some(x => x !== null && typeof x !== "string" && typeof x !== "number" && typeof x !== "object")) fail("INVALID_OSM_POWER_FEATURE"); const id = osmId as number; if (ids.has(id)) fail("INVALID_OSM_POWER_FEATURE"); if (kind === "line") { if (geometry.type !== "LineString" || !Array.isArray(geometry.coordinates) || geometry.coordinates.length < 2 || !geometry.coordinates.every(validPoint) || typeof p.line_type !== "string") fail("INVALID_OSM_POWER_FEATURE"); } else if (geometry.type !== "Point" || !validPoint(geometry.coordinates)) fail("INVALID_OSM_POWER_FEATURE"); ids.add(id); const row: Record<string, unknown> = { record_id: `osm-${kind}-${id}`, ...Object.fromEntries(fields.map(name => [name, p[name]])), geometry: { type: geometry.type, coordinates: geometry.coordinates } }; if (index >= count) fail("INVALID_OSM_POWER_FEATURE"); return row; }); return { rows, bytes: value.byteLength }; }
async function load(kind: "line" | "tower", url: string, checksum: string, fetcher: Fetcher, signal?: AbortSignal): Promise<{ snapshot: Snapshot; cacheHit: boolean }> { const cached = cache.get(kind); if (cached) return { snapshot: cached, cacheHit: true }; if (signal?.aborted) throw signal.reason; const controller = new AbortController(); const timer = setTimeout(() => controller.abort(), 15_000); try { const response = await fetcher(url, { signal: controller.signal, credentials: "same-origin", redirect: "error" }); if (!response.ok || response.headers.get("content-type")?.includes("text/html")) fail("OSM_POWER_SOURCE_UNAVAILABLE"); const source = await bytes(response); if (await digest(source) !== checksum) fail("OSM_POWER_SOURCE_SHA_MISMATCH"); const snapshot = parse(kind, source); cache.set(kind, snapshot); return { snapshot, cacheHit: false }; } finally { clearTimeout(timer); } }
function reader(kind: "line" | "tower", url: string, checksum: string, descriptor: DatasetDescriptor, fetcher: Fetcher) { return async (_p: Readonly<Record<string, Scalar>>, signal?: AbortSignal, context?: QueryReadContext): Promise<AdapterSnapshot> => { if (!context?.bbox) fail("BBOX_REQUIRED"); return withLoading(`research:osm-power-${kind}s`, `載入 OSM 電網${kind === "line" ? "線" : "塔"}快照`, (async () => { const { snapshot, cacheHit } = await load(kind, url, checksum, fetcher, signal); const source: SourceReceipt = { sourceId: descriptor.datasetId, version: `sha256:${checksum}`, acquiredAt: new Date().toISOString(), checksumSha256: checksum, reference: url }; return { rows: snapshot.rows, source, coverage: descriptor.coverage, freshness: "stale", exclusions: {}, rowsScanned: snapshot.rows.length, bytesScanned: snapshot.bytes, downloadedBytes: cacheHit ? 0 : snapshot.bytes, requests: cacheHit ? 0 : 1, cacheHit }; })()); }; }
export function clearOsmPowerNetworkOwnerCache(): void { cache.clear(); }
export function createOsmPowerLinesOwnerAdapter(fetcher: Fetcher = fetch): QueryAdapter { return createLineDatasetAdapter(osmPowerLinesOwnerDescriptor, reader("line", LINE_URL, LINE_SHA256, osmPowerLinesOwnerDescriptor, fetcher)); }
export function createOsmPowerTowersOwnerAdapter(fetcher: Fetcher = fetch): QueryAdapter { return createPointDatasetAdapter(osmPowerTowersOwnerDescriptor, reader("tower", TOWER_URL, TOWER_SHA256, osmPowerTowersOwnerDescriptor, fetcher)); }
export const osmPowerLinesOwnerAdapter = createOsmPowerLinesOwnerAdapter(); export const osmPowerTowersOwnerAdapter = createOsmPowerTowersOwnerAdapter();
