import { boundedAccess, DEFAULT_VALUE_SEMANTICS, type DatasetDescriptor, type DatasetField, type Scalar, type SourceReceipt } from "./dataContracts";
import { loadPointDataset } from "./pointDatasetAdapter";
import { createPointDatasetAdapter, type AdapterSnapshot } from "./queryAdapters";
import type { QueryAdapter } from "./queryExecutor";

const ROOT = "/__local-research-owner-only/tourism-hospitality";
type Family = Readonly<{ datasetId: string; label: string; layerRef: "tourHotels" | "tourRestaurants"; slug: "hotels" | "restaurants"; idField: string; sourceSha256: string; manifestSha256: string; rows: number; observedAt: string; safeFields: readonly string[]; excludedFields: string; description: string; coverage: string; fieldDefs: readonly DatasetField[] }>;
const common = [{ name: "record_id", type: "string" as const, nullable: false, nullMeaning: null, unit: null }, { name: "geometry", type: "json" as const, nullable: false, nullMeaning: null, unit: null }];
const families: readonly Family[] = [
  { datasetId: "tw-tour-hotels-owner-20260722", label: "觀光署旅宿（2026-07-22 owner-only 快照）", layerRef: "tourHotels", slug: "hotels", idField: "HotelID", sourceSha256: "6eb9e3dd6ccc9ea9a6b7746231001e70e7d753ecc5794c7e1fb31fe56e82d9e0", manifestSha256: "8b70d194e402e1026a6789a2fb56d3ebd2dc46572cf7f873439485037fde30d3", rows: 15_654, observedAt: "2026-07-22", safeFields: ["HotelID", "HotelName", "City", "CityCode", "Town", "TownCode", "HotelClasses", "HotelStars", "TotalRooms", "LowestPrice", "CeilingPrice", "TotalCapacity", "ParkingSpaces"], excludedFields: "address、電話、長描述與重複 lat/lon", description: "觀光署 V2.1 旅宿固定快照。每次必須給 bbox；可作來源 WGS84 Point 的 bbox 與直線參考最近點，不能推論營業、空房、房價可訂性、入口、步行或大眾運輸可達性。", coverage: "原始 15,656 筆中 2 筆無效座標已排除，15,654 筆 Point。HotelStars=null 是來源未提供星等；HotelStars=0 是來源值，不能視為 null。LowestPrice=0 是來源數值，不能改成缺值或可訂價格。", fieldDefs: [...common.slice(0, 1), { name: "HotelID", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "HotelName", type: "string", nullable: false, nullMeaning: null, unit: null }, ...["City", "CityCode", "Town", "TownCode", "HotelClasses"].map(name => ({ name, type: "string" as const, nullable: true, nullMeaning: "來源未提供", unit: null })), { name: "HotelStars", type: "number", nullable: true, nullMeaning: "來源未提供星等；與 0 不同", unit: "star" }, ...["TotalRooms", "LowestPrice", "CeilingPrice", "TotalCapacity", "ParkingSpaces"].map(name => ({ name, type: "number" as const, nullable: true, nullMeaning: name === "LowestPrice" ? "來源未提供最低房價；與 0 不同" : "來源未提供", unit: name.includes("Price") ? "TWD" : null })), common[1]! ] },
  { datasetId: "tw-tour-restaurants-owner-20260723", label: "觀光署餐飲（2026-07-23 owner-only 快照）", layerRef: "tourRestaurants", slug: "restaurants", idField: "id", sourceSha256: "f78dcd2d99aacdc3607c2230d8280945ab67e17948b6e237e3a01b1abffd19f9", manifestSha256: "1b855a0198ffe0a53cc339972dec2a037dd1f313814ae76fd1f8ccfb0d25eeb9", rows: 3_688, observedAt: "2026-07-23", safeFields: ["id", "name", "cuisine_class", "city", "town", "service_time"], excludedFields: "地址、電話、長描述與重複 lat/lon", description: "觀光署 V2.1 餐飲固定快照。每次必須給 bbox；可作來源 WGS84 Point 的 bbox 與直線參考最近點，不能推論目前營業、訂位、入口、步行或大眾運輸可達性。", coverage: "原始 3,690 筆中 2 筆無效座標已排除，3,688 筆 Point。cuisine_class 是未對照的來源代碼；service_time 空值是來源未提供，不能當成停業或全天開放。", fieldDefs: [...common.slice(0, 1), { name: "id", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "name", type: "string", nullable: false, nullMeaning: null, unit: null }, { name: "cuisine_class", type: "string", nullable: true, nullMeaning: "來源未提供類別；代碼未附官方對照", unit: null }, { name: "city", type: "string", nullable: true, nullMeaning: "來源未提供", unit: null }, { name: "town", type: "string", nullable: true, nullMeaning: "來源未提供", unit: null }, { name: "service_time", type: "string", nullable: true, nullMeaning: "來源未提供營業時間；不表示停業或全天開放", unit: null }, common[1]! ] },
];
function fail(code: string): never { throw new Error(code); }
function descriptor(family: Family): DatasetDescriptor {
  const reference = `/research/tourism-hospitality/${family.slug}/source-identity/sha256-${family.sourceSha256}`;
  return { schemaVersion: "pulse-dataset/0.1", datasetId: family.datasetId, label: family.label, description: family.description, layerRefs: [family.layerRef], kind: "point", recordGrain: "place", primaryKey: ["record_id"], fields: family.fieldDefs, geometry: { type: "Point", crs: "EPSG:4326", role: "actual", precision: "觀光署來源 WGS84 Point；可做 bbox 和直線參考距離，並非入口、道路距離、步行或 transit 可達性。", spatialAnalysisEligible: true }, timeFields: [], coverage: family.coverage, license: "政府資料開放授權條款-第1版（OGDL-Taiwan-1.0）；owner-only localhost sidecar。", valueSemantics: { ...DEFAULT_VALUE_SEMANTICS, null: family.coverage, zero: "數值 0 是來源觀測值，不能轉為 null、缺值或營業狀態。", stale: `固定 ${family.observedAt} 快照不代表目前營業、供應、價格、訂位、空房、入口或交通可達性。` }, versions: [{ versionId: `sha256:${family.sourceSha256}`, observedAt: family.observedAt, availableAt: null, checksumSha256: family.sourceSha256, mutable: false }], source: { publisher: "交通部觀光署", reference, lineage: `官方 V2.1 ZIP -> taipei-gis-analytics processed GeoJSON SHA-256 ${family.sourceSha256} -> safe-field owner-only gzip partitions；移除 ${family.excludedFields}。` }, access: boundedAccess({ mode: "owner_only", method: "pmtiles_sidecar", fields: family.fieldDefs.map(field => field.name), filters: family.fieldDefs.filter(field => !["record_id", "geometry"].includes(field.name)).map(field => field.name), supportsBbox: true, maxRowsPerQuery: 100, maxScanRows: 20_000, maxSourceBytes: 8 * 1024 * 1024 }), supportedOperations: ["query_records", "nearest", "aggregate"], adapterId: "tourism-hospitality-owner-partitions-v1" };
}
function adapter(family: Family): QueryAdapter {
  const dataDescriptor = descriptor(family);
  return createPointDatasetAdapter(dataDescriptor, async (_parameters: Readonly<Record<string, Scalar>>, signal?: AbortSignal, context?: { bbox?: readonly [number, number, number, number] }): Promise<AdapterSnapshot> => {
    if (!context?.bbox) fail("BBOX_REQUIRED");
    const snapshot = await loadPointDataset({ datasetId: family.datasetId, url: `/research/tourism-hospitality/${family.slug}/source-identity/sha256-${family.sourceSha256}`, idField: family.idField, safeFields: family.safeFields, spatialPartition: { manifestUrl: `${ROOT}/${family.slug}/manifest.json`, manifestSha256: family.manifestSha256, sourceSha256: family.sourceSha256 } }, { bbox: context.bbox, signal });
    if (snapshot.checksumSha256 !== family.sourceSha256 || snapshot.exclusions.missing_geometry || snapshot.exclusions.non_point_geometry || snapshot.exclusions.invalid_geometry) fail("TOURISM_HOSPITALITY_OWNER_SOURCE_SEMANTICS_MISMATCH");
    const source: SourceReceipt = { sourceId: family.datasetId, version: `sha256:${family.sourceSha256}`, acquiredAt: snapshot.acquiredAt, checksumSha256: family.sourceSha256, reference: `/research/tourism-hospitality/${family.slug}/source-identity/sha256-${family.sourceSha256}` };
    return { rows: snapshot.rows, source, coverage: dataDescriptor.coverage, freshness: "stale", exclusions: snapshot.exclusions, rowsScanned: snapshot.rows.length, bytesScanned: snapshot.bytes, downloadedBytes: snapshot.downloadedBytes, requests: snapshot.requests, cacheHit: snapshot.cacheHit };
  });
}
export const tourismHotelOwnerAdapter = adapter(families[0]!);
export const tourismRestaurantOwnerAdapter = adapter(families[1]!);
export const tourismHospitalityOwnerDescriptors = families.map(descriptor);
