export type WebsiteAction = "search_layers" | "get_layer_details" | "set_layers" | "readback";
export interface ScreeningLayer { key: string; label: string; theme: string | null; group: string | null; sourceKinds: readonly string[]; sourceStatus: string; sourceTime: string; license: string; coverage: string; geometryPrecision: string; batchId: string; decision: { status: "decided" | "unknown"; relevant: boolean | null; probability: number | null; answerType: "noul" | null; confidence: null; }; }
export interface ScreeningBatch { batchId: string; requestId: string | null; requestBytes: number; candidateCount: number; durationMs: number; status: "completed" | "error" | "planned"; error: string | null; startedAt?: string; endedAt?: string; }
/** Direct UI contract for scripts/research/jev-layer-screening-run.ts receipt v1. */
export interface JevRunReceipt { version: "jev-layer-screening-receipt/v1"; mode: "live" | "dry-run"; runId: string; query: string; provider: "openrouter"; model: string; startedAt: string; endedAt: string; wallDurationMs: number; relevanceThreshold: number; manifestFingerprint: string; indexFingerprint: string; candidateCount: number; lockedExcludedCount: number; batches: readonly ScreeningBatch[]; layers: readonly ScreeningLayer[]; plannedWebsiteActions: readonly { action: WebsiteAction; executed: false; note: string; }[]; websiteReady: false; }
function object(value: unknown): value is Record<string, unknown> { return typeof value === "object" && value !== null && !Array.isArray(value); }
function layer(value: unknown): value is ScreeningLayer { return object(value) && typeof value.key === "string" && typeof value.label === "string" && Array.isArray(value.sourceKinds) && object(value.decision) && ["decided", "unknown"].includes(String(value.decision.status)) && (value.decision.relevant === null || typeof value.decision.relevant === "boolean") && (value.decision.probability === null || (typeof value.decision.probability === "number" && value.decision.probability >= 0 && value.decision.probability <= 1)) && (value.decision.answerType === null || value.decision.answerType === "noul") && value.decision.confidence === null; }
function batch(value: unknown): value is ScreeningBatch { return object(value) && typeof value.batchId === "string" && typeof value.durationMs === "number" && ["completed", "error", "planned"].includes(String(value.status)); }
function action(value: unknown): value is JevRunReceipt["plannedWebsiteActions"][number] { return object(value) && ["search_layers", "get_layer_details", "set_layers", "readback"].includes(String(value.action)) && value.executed === false && typeof value.note === "string"; }
export function parseJevRunReceipt(value: unknown): JevRunReceipt | null { if (!object(value) || value.version !== "jev-layer-screening-receipt/v1" || !["live", "dry-run"].includes(String(value.mode)) || typeof value.runId !== "string" || typeof value.query !== "string" || value.provider !== "openrouter" || typeof value.model !== "string" || typeof value.startedAt !== "string" || typeof value.endedAt !== "string" || typeof value.wallDurationMs !== "number" || typeof value.relevanceThreshold !== "number" || typeof value.manifestFingerprint !== "string" || typeof value.indexFingerprint !== "string" || typeof value.candidateCount !== "number" || typeof value.lockedExcludedCount !== "number" || !Array.isArray(value.batches) || !value.batches.every(batch) || !Array.isArray(value.layers) || !value.layers.every(layer) || !Array.isArray(value.plannedWebsiteActions) || !value.plannedWebsiteActions.every(action) || value.websiteReady !== false) return null; return value as unknown as JevRunReceipt; }
/** Receipt cannot introduce a non-displayable layer into the POC. */
export function receiptLayersForCandidates<T extends { key: string }>(receipt: JevRunReceipt, candidates: readonly T[]): readonly (ScreeningLayer & { candidate: T })[] { const allowed = new Map(candidates.map((candidate) => [candidate.key, candidate])); return receipt.layers.flatMap((item) => { const candidate = allowed.get(item.key); return candidate ? [{ ...item, candidate }] : []; }); }

export async function fingerprintSearchIndex(items: readonly { key: string; label: string; theme: string | null; group: string | null; topics: readonly string[] }[]): Promise<string> {
  const payload = JSON.stringify(items.map((item) => [item.key, item.label, item.theme, item.group, item.topics]));
  const digest = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(payload));
  return [...new Uint8Array(digest)].map((byte) => byte.toString(16).padStart(2, "0")).join("");
}
