#!/usr/bin/env python3
"""
Phase 4A — Generate src/data/upstreamRegistry.ts from match_final.csv

The registry maps each pulse layer_key → its upstream catalog dataset_id(s)
plus metadata (provider agency, lifecycle, confidence).

Reads:
  - scratchpad/audit/match_final.csv
  - scratchpad/audit/catalog_datasets.csv
Writes:
  - src/data/upstreamRegistry.ts
"""
import csv
from pathlib import Path
from collections import defaultdict

SCRATCH = Path("/private/tmp/claude-501/-Users-migu-Desktop-----gen-ai-try-ichef-----GIS-mini-taiwan-pulse/6c00383b-969d-4fee-96d3-b7971926a182/scratchpad/audit")
PULSE_ROOT = Path("/Users/migu/Desktop/資料庫/gen_ai_try/ichef_工作用/GIS/mini-taiwan-pulse")
OUT_TS = PULSE_ROOT / "src/data/upstreamRegistry.ts"

with (SCRATCH / "match_final.csv").open() as f:
    matches = list(csv.DictReader(f))
with (SCRATCH / "catalog_datasets.csv").open() as f:
    catalog = {r["dataset_id"]: r for r in csv.DictReader(f)}
with (SCRATCH / "pulse_layers.csv").open() as f:
    pulse = {r["layer_key"]: r for r in csv.DictReader(f)}

# Derivation map: pulse_only layers — what they're derived from + how
DERIVATION = {
    "medIsochrone": {
        "derivedFrom": ["medHospital", "medClinic"],
        "processing": "OSRM 路網等時圈計算（駕車時間 5/10/15/30 分鐘）— 從醫療 POI 出發沿實際路網擴散",
    },
    "medDesert": {
        "derivedFrom": ["medIsochrone"],
        "processing": "等時圈反演 — 距任一醫療設施駕車 > 30 分鐘的村里標為醫療沙漠",
    },
    "fireIsochrone": {
        "derivedFrom": ["fireStations"],
        "processing": "OSRM 路網等時圈計算（救援抵達 ≤ 5/8/10 分鐘）— 從消防分隊出發",
    },
}

# Group catalogs assigned to same layer
layer_to_datasets = defaultdict(list)
for m in matches:
    if m["dataset_id"]:
        layer_to_datasets[m["layer_key"]].append({
            "dataset_id": m["dataset_id"],
            "confidence": m["confidence"],
            "rule": m["rule"],
        })

# ── Generate TypeScript ──
def ts_escape(s):
    if s is None:
        return "''"
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'") + "'"


def ts_str_array(items):
    return "[" + ", ".join(ts_escape(i) for i in items) + "]"


lines = []
lines.append("// ══════════════════════════════════════════════════════════════════")
lines.append("//  Upstream Registry — pulse layer ↔ taipei-gis-analytics catalog dataset")
lines.append("// ══════════════════════════════════════════════════════════════════")
lines.append("//")
lines.append("// Generated by scripts/audit/06_apply_to_pulse.py from match_final.csv.")
lines.append("// SSOT for upstream data sources is taipei-gis-analytics/docs/data-catalog/")
lines.append("// This file is the bridge: layer_key → catalog dataset_id.")
lines.append("//")
lines.append("// Status values:")
lines.append("//   verified         — bridged to one or more catalog datasets")
lines.append("//   pulse_only       — pure-frontend layer (derived / animated / no upstream)")
lines.append("//   catalog_missing  — needs new entry in catalog before bridging")
lines.append("")
lines.append("import type { LayerVisibility } from '../types';")
lines.append("")
lines.append("export type UpstreamStatus = 'verified' | 'pulse_only' | 'catalog_missing';")
lines.append("export type UpstreamConfidence = 'HIGH' | 'MED' | 'LOW';")
lines.append("")
lines.append("export interface UpstreamDataset {")
lines.append("  /** catalog dataset_id (matches frontmatter in taipei-gis-analytics/docs/data-catalog/<theme>/<dataset_id>.md) */")
lines.append("  datasetId: string;")
lines.append("  /** match confidence — HIGH = explicit frontend_target / exact name; MED = normalized variant; LOW = fuzzy */")
lines.append("  confidence: UpstreamConfidence;")
lines.append("}")
lines.append("")
lines.append("export interface UpstreamRef {")
lines.append("  status: UpstreamStatus;")
lines.append("  /** Primary catalog dataset (empty array for pulse_only / catalog_missing) */")
lines.append("  datasets: UpstreamDataset[];")
lines.append("  /** For status='pulse_only': which other layer_keys / datasets this is derived from */")
lines.append("  derivedFrom?: string[];")
lines.append("  /** For status='pulse_only': short description of how the data is generated/processed */")
lines.append("  processing?: string;")
lines.append("  /** Free-form reason when status != 'verified' */")
lines.append("  note?: string;")
lines.append("}")
lines.append("")
lines.append("export const UPSTREAM_REGISTRY: Record<keyof LayerVisibility, UpstreamRef> = {")

# Iterate in pulse_layers.csv order (deterministic)
for layer_key in pulse:
    m = next((m for m in matches if m["layer_key"] == layer_key), None)
    if not m:
        # Shouldn't happen — but defensively
        lines.append(f"  {layer_key}: {{ status: 'catalog_missing', datasets: [], note: 'no match record' }},")
        continue

    status = m["status"]
    if status == "verified":
        datasets = layer_to_datasets.get(layer_key, [])
        if not datasets:
            lines.append(f"  {layer_key}: {{ status: 'catalog_missing', datasets: [] }},")
            continue
        ds_strs = []
        for d in datasets:
            ds_strs.append(f"{{ datasetId: {ts_escape(d['dataset_id'])}, confidence: {ts_escape(d['confidence'])} }}")
        lines.append(f"  {layer_key}: {{")
        lines.append(f"    status: 'verified',")
        lines.append(f"    datasets: [{', '.join(ds_strs)}],")
        lines.append(f"  }},")
    elif status == "pulse_only":
        note = m["notes"][:80].replace("'", "")
        deriv = DERIVATION.get(layer_key)
        if deriv:
            lines.append(f"  {layer_key}: {{")
            lines.append(f"    status: 'pulse_only',")
            lines.append(f"    datasets: [],")
            lines.append(f"    derivedFrom: {ts_str_array(deriv['derivedFrom'])},")
            lines.append(f"    processing: {ts_escape(deriv['processing'])},")
            lines.append(f"    note: {ts_escape(note)},")
            lines.append(f"  }},")
        else:
            lines.append(f"  {layer_key}: {{ status: 'pulse_only', datasets: [], note: {ts_escape(note)} }},")
    elif status == "catalog_missing":
        note = m["notes"][:80].replace("'", "")
        lines.append(f"  {layer_key}: {{ status: 'catalog_missing', datasets: [], note: {ts_escape(note)} }},")
    else:
        # name_mismatch (shouldn't happen post-merge, but)
        lines.append(f"  {layer_key}: {{ status: 'catalog_missing', datasets: [], note: 'unclassified after Phase 3' }},")

# Append stub entries for LayerVisibility keys not in THEMES (stale colors / not yet wired)
# Read LAYER_COLORS keys from layerCatalog.ts to know full LayerVisibility surface
import re as _re
catalog_ts = (PULSE_ROOT / "src/components/sidebar/layerCatalog.ts").read_text(encoding="utf-8")
# Extract LAYER_COLORS keys (export const LAYER_COLORS block)
m = _re.search(r"export const LAYER_COLORS[^{]*\{([\s\S]*?)\n\};", catalog_ts)
if m:
    color_block = m.group(1)
    color_keys = _re.findall(r"^\s*([a-zA-Z][a-zA-Z0-9_]*):", color_block, _re.M)
    themes_keys = set(pulse.keys())
    stale = [k for k in color_keys if k not in themes_keys]
    if stale:
        lines.append("  // ── Stub entries for LayerVisibility keys not in THEMES (stale, unused, or pending wiring) ──")
        for k in stale:
            lines.append(f"  {k}: {{ status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' }},")
lines.append("};")
lines.append("")
lines.append("// ── Convenience helpers ──")
lines.append("")
lines.append("export function getUpstreamFor(layerKey: keyof LayerVisibility): UpstreamRef {")
lines.append("  return UPSTREAM_REGISTRY[layerKey];")
lines.append("}")
lines.append("")
lines.append("export function getAllVerifiedDatasets(): Set<string> {")
lines.append("  const out = new Set<string>();")
lines.append("  for (const ref of Object.values(UPSTREAM_REGISTRY)) {")
lines.append("    if (ref.status === 'verified') {")
lines.append("      for (const d of ref.datasets) out.add(d.datasetId);")
lines.append("    }")
lines.append("  }")
lines.append("  return out;")
lines.append("}")

OUT_TS.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"✓ Written: {OUT_TS}")
print(f"  Verified layers:        {sum(1 for m in matches if m['status']=='verified')}")
print(f"  pulse_only layers:      {sum(1 for m in matches if m['status']=='pulse_only')}")
print(f"  catalog_missing layers: {sum(1 for m in matches if m['status']=='catalog_missing')}")
