// FeatureInfo popup 的 renderer registry — layerType → panel 元件 + 標題。
//
// 新增 layer 的 popup 接線只要：寫 panel 元件（放對應 domain 檔）→ 此處
// 各加一行。layerConsistency / featureInfoRegistry 測試會守備漏接。
import type { FC } from "react";
import type { FeatureInfo } from "../../types";
import {
  SubmarineCablePanel, LandingStationPanel, SchoolPanel, ConvenienceStorePanel,
  LighthousePanel, PortPanel, AirportPanel, CctvPanel, EtcGantryPanel,
  ServiceAreaPanel, ServiceAreaPolygonPanel, TaxiStandPanel,
} from "./infraPanels";
import {
  WeatherStationPanel, BikeStationPanel, BusStationPanel, RailStationPanel, ShipPanel,
} from "./transportPanels";
import {
  WaterFacilityPanel, WaterMonitorPanel, WaterDetentionBasinPanel, WaterDamPanel,
  RiverLevelPanel, GroundwaterPanel, FloodSensorPanel, RainGaugePanel,
  WaterReservoirPolyPanel,
} from "./waterPanels";
import { TaipeiSewerPanel, TaipeiPumbPanel, TaipeiEvacuatePanel } from "./taipeiWicPanels";
import { NewsEventPanel, DisasterAlertPanel, RoadEventPanel, ActiveFaultPanel } from "./eventPanels";
import { AqiStationPanel, MicroSensorPanel } from "./airPanels";
import { WasteFacilityPanel, WasteDisposalPointPanel, WasteCleaningSquadPanel } from "./wastePanels";
import {
  AgriSoilPanel, AgriSoilFertilityPanel, AgriLeisureFarmZonesPanel, AgriCropSuitabilityPanel,
  AgriRuralRegenPanel, AgriPOIPanel, AgriCompanyPanel, FarmRoadsPanel, EcoNetworkZonesPanel,
} from "./agriPanels";
import { HikingTrailsPanel, ForestryGenericPanel } from "./forestryPanels";
import { FireEventPanel, FireStationPanel, FireHydrantPanel, FireIsochronePanel } from "./firePanels";
import { LivestockFarmPanel, LivestockSlaughterPanel, LivestockFeedPanel, LivestockMarketPanel } from "./livestockPanels";
import { SportsVenuePanel } from "./sportsPanels";
import { MedicalPOIPanel, MedicalIsochronePanel } from "./medicalPanels";
import { SatellitePanel } from "./satellitePanels";
import { PowerPlantPanel, OsmSubstationPanel, OsmPowerLinePanel, OsmPowerTowerPanel, OsmWindTurbinePanel, OsmSolarFarmPanel, OsmPowerPlantStaticPanel, OffshoreWindZonePanel, IslandPowerFacilityPanel, FossilFuelFacilityPanel, GeothermalWellPanel, RenewablePermitTaipeiPanel, EvChargingPanel,
  GasStationCpcPanel, GasStationFpccPanel, GasStationTaisugarPanel, GasStationOtherPanel,
  GasStationCanonicalPanel, LpgSubpackagingPanel, LpgRetailersPanel, LngTerminalPanel,
  PipelineGasPanel, PipelineOilGasPanel,
  IndustrialRefineryPanel, IndustrialStorageTankPanel, IndustrialPowerPlantPanel,
  CoalTerminalPanel,
  GasCoverageAllPanel, GasCoverageCpcPanel, GasCoverageFpccPanel, GasCoverageTaisugarPanel,
  EvIslandPanel,
} from "./energyPanels";
import { LightningStrikePanel, NuclearStationPanel } from "./hazardPanels";
import { EarthquakeGlobalPanel, TyphoonTrackPanel, ClimateFieldPanel } from "./globalClimatePanels";
import {
  CountyBoundaryPanel, TownshipBoundaryPanel, VillageBoundaryPanel,
  Contour25kPanel, ContourDtm20Panel, OsmRoadDrivePanel,
} from "./baseMapPanels";
import {
  PoliceStationPanel, WomenChildWarningPanel, SpeedCameraPanel, SpeedZoneSegmentPanel,
  CourtPanel, ProsecutorsOfficePanel, CorrectionalFacilityPanel, CourtJurisdictionPanel,
  CrimeAreaMonthlyPanel, TheftTaoyuanPanel, TrafficAccidentYearlyPanel, AccidentTaipeiPanel,
  A1AccidentRealtimePanel,
  InvestigationBureauPanel, AntiCorruptionOfficePanel, ImmigrationOfficePanel, CoastGuardStationPanel,
  CivilDefenseShelterPanel,
  AviationAirspacePanel,
  DroneZonesPanel,
  PoliceIsoSubstationPanel, PoliceIsoPrecinctPanel, PoliceIsoCityDeptPanel,
} from "./policeJusticePanels";
import { ChatHighlightPanel } from "./shared";

export interface PanelProps {
  props: Record<string, unknown>;
}

/**
 * layerType → panel 元件。
 * Partial：groundwaterWell / iotWraRiver / iotWraStructure 自始沒有專屬 panel
 * （popup 只顯示 header），維持原行為 — 見 featureInfoRegistry 測試的 baseline。
 */
export const PANEL_REGISTRY: Partial<Record<FeatureInfo["layerType"], FC<PanelProps>>> = {
  submarineCable: SubmarineCablePanel,
  landingStation: LandingStationPanel,
  school: SchoolPanel,
  convenienceStore: ConvenienceStorePanel,
  weatherStation: WeatherStationPanel,
  bikeStation: BikeStationPanel,
  busStation: BusStationPanel,
  ship: ShipPanel,
  lighthouse: LighthousePanel,
  railStation: RailStationPanel,
  port: PortPanel,
  airport: AirportPanel,
  cctv: CctvPanel,
  etcGantry: EtcGantryPanel,
  serviceArea: ServiceAreaPanel,
  serviceAreaPolygon: ServiceAreaPolygonPanel,
  taxiStand: TaxiStandPanel,
  activeFault: ActiveFaultPanel,
  newsEvent: NewsEventPanel,
  disasterAlert: DisasterAlertPanel,
  roadEvent: RoadEventPanel,
  aqiStation: AqiStationPanel,
  microSensor: MicroSensorPanel,
  waterFacility: WaterFacilityPanel,
  waterMonitor: WaterMonitorPanel,
  waterDam: WaterDamPanel,
  waterReservoirPoly: WaterReservoirPolyPanel,
  waterDetentionBasin: WaterDetentionBasinPanel,
  rainGauge: RainGaugePanel,
  riverLevel: RiverLevelPanel,
  groundwater: GroundwaterPanel,
  floodSensor: FloodSensorPanel,
  floodSensorIsochrone: FloodSensorPanel,
  taipeiSewer: TaipeiSewerPanel,
  taipeiEvacuate: TaipeiEvacuatePanel,
  taipeiPumb: TaipeiPumbPanel,
  wasteFacility: WasteFacilityPanel,
  wasteDisposalPoint: WasteDisposalPointPanel,
  wasteCleaningSquad: WasteCleaningSquadPanel,
  agriRetail: AgriCompanyPanel,
  agriProduceWholesale: AgriCompanyPanel,
  agriWholesaleMarket: AgriCompanyPanel,
  farmRoads: FarmRoadsPanel,
  ecoNetworkZones: EcoNetworkZonesPanel,
  forestryPolygon: ForestryGenericPanel,
  forestryLine: ForestryGenericPanel,
  forestryPOI: ForestryGenericPanel,
  hikingTrails: HikingTrailsPanel,
  agriPOI: AgriPOIPanel,
  agriRuralRegen: AgriRuralRegenPanel,
  agriSoil: AgriSoilPanel,
  agriSoilFertility: AgriSoilFertilityPanel,
  agriLeisureFarmZones: AgriLeisureFarmZonesPanel,
  agriCropSuitability: AgriCropSuitabilityPanel,
  fireEvent: FireEventPanel,
  fireStation: FireStationPanel,
  fireHydrant: FireHydrantPanel,
  fireIsochrone: FireIsochronePanel,
  medicalPOI: MedicalPOIPanel,
  medicalIsochrone: MedicalIsochronePanel,
  satellite: SatellitePanel,
  powerPlant: PowerPlantPanel,
  osmSubstation: OsmSubstationPanel,
  osmPowerLine: OsmPowerLinePanel,
  osmPowerTower: OsmPowerTowerPanel,
  osmWindTurbine: OsmWindTurbinePanel,
  osmSolarFarm: OsmSolarFarmPanel,
  osmPowerPlantStatic: OsmPowerPlantStaticPanel,
  offshoreWindZone: OffshoreWindZonePanel,
  islandPowerFacility: IslandPowerFacilityPanel,
  fossilFuelFacility: FossilFuelFacilityPanel,
  geothermalWell: GeothermalWellPanel,
  renewablePermitTaipei: RenewablePermitTaipeiPanel,
  evCharging: EvChargingPanel,
  // 化石燃料 14 layer
  gasStationCpc: GasStationCpcPanel,
  gasStationFpcc: GasStationFpccPanel,
  gasStationTaisugar: GasStationTaisugarPanel,
  gasStationOther: GasStationOtherPanel,
  gasStationCanonical: GasStationCanonicalPanel,
  lpgSubpackaging: LpgSubpackagingPanel,
  lpgRetailers: LpgRetailersPanel,
  lngTerminal: LngTerminalPanel,
  pipelineGas: PipelineGasPanel,
  pipelineOilGas: PipelineOilGasPanel,
  industrialRefinery: IndustrialRefineryPanel,
  industrialStorageTank: IndustrialStorageTankPanel,
  industrialPowerPlant: IndustrialPowerPlantPanel,
  coalTerminal: CoalTerminalPanel,
  // 雲林 POC 覆蓋分析
  gasCoverageAll: GasCoverageAllPanel,
  gasCoverageCpc: GasCoverageCpcPanel,
  gasCoverageFpcc: GasCoverageFpccPanel,
  gasCoverageTaisugar: GasCoverageTaisugarPanel,
  evIsland: EvIslandPanel,
  lightningStrike: LightningStrikePanel,
  nuclearStation: NuclearStationPanel,
  earthquakeGlobal: EarthquakeGlobalPanel,
  typhoonTrack: TyphoonTrackPanel,
  climateField: ClimateFieldPanel,
  // Base map
  countyBoundary: CountyBoundaryPanel,
  townshipBoundary: TownshipBoundaryPanel,
  villageBoundary: VillageBoundaryPanel,
  contour25k: Contour25kPanel,
  contourDtm20: ContourDtm20Panel,
  osmRoadDrive: OsmRoadDrivePanel,
  // 警政司法民防 17 layer
  policeStation: PoliceStationPanel,
  womenChildWarning: WomenChildWarningPanel,
  speedCamera: SpeedCameraPanel,
  speedZoneSegment: SpeedZoneSegmentPanel,
  court: CourtPanel,
  prosecutorsOffice: ProsecutorsOfficePanel,
  correctionalFacility: CorrectionalFacilityPanel,
  courtJurisdiction: CourtJurisdictionPanel,
  crimeAreaMonthly: CrimeAreaMonthlyPanel,
  theftTaoyuan: TheftTaoyuanPanel,
  trafficAccidentYearly: TrafficAccidentYearlyPanel,
  accidentTaipei: AccidentTaipeiPanel,
  a1AccidentRealtime: A1AccidentRealtimePanel,
  investigationBureau: InvestigationBureauPanel,
  antiCorruptionOffice: AntiCorruptionOfficePanel,
  immigrationOffice: ImmigrationOfficePanel,
  coastGuardStation: CoastGuardStationPanel,
  civilDefenseShelter: CivilDefenseShelterPanel,
  aviationControl: AviationAirspacePanel,
  aviationRestricted: AviationAirspacePanel,
  droneNoFlyZone: DroneZonesPanel,
  droneRestrictedZone: DroneZonesPanel,
  policeIsoSubstation: PoliceIsoSubstationPanel,
  policeIsoPrecinct: PoliceIsoPrecinctPanel,
  policeIsoCityDept: PoliceIsoCityDeptPanel,
  // AI 助手標記點
  chatHighlight: ChatHighlightPanel,
  // 🐷 畜牧
  livestockFarm: LivestockFarmPanel,
  livestockSlaughter: LivestockSlaughterPanel,
  livestockFeed: LivestockFeedPanel,
  livestockMarket: LivestockMarketPanel,
  // 🏟️ 運動場館
  sportsVenue: SportsVenuePanel,
};

export const HEADER_LABELS: Record<FeatureInfo["layerType"], string> = {
  submarineCable: "通訊海纜",
  landingStation: "海纜登陸站",
  school: "學校",
  convenienceStore: "超商",
  weatherStation: "氣象站",
  bikeStation: "公共自行車站",
  busStation: "公車站",
  ship: "船舶",
  lighthouse: "燈塔",
  railStation: "車站",
  port: "港口",
  airport: "機場",
  cctv: "道路攝影機",
  etcGantry: "ETC 收費門架",
  serviceArea: "國道服務區",
  serviceAreaPolygon: "國道服務區範圍",
  taxiStand: "計程車招呼站",
  activeFault: "活動斷層",
  newsEvent: "新聞事件",
  disasterAlert: "災害示警",
  roadEvent: "即時路況",
  aqiStation: "空氣品質測站",
  microSensor: "微型感測器",
  waterFacility: "水利設施",
  waterMonitor: "水資源監測站",
  waterDam: "水庫 / 壩體",
  waterReservoirPoly: "水庫蓄水範圍",
  waterDetentionBasin: "滯洪池",
  rainGauge: "即時雨量站",
  riverLevel: "河川水位站",
  groundwater: "地下水井",
  groundwaterWell: "地下水井",
  iotWraRiver: "IoT 河川水位站",
  iotWraStructure: "IoT 水工結構",
  floodSensor: "都市淹水感測器",
  floodSensorIsochrone: "淹水 3 分步行圈",
  taipeiSewer: "北市雨水下水道水位",
  taipeiEvacuate: "北市疏散門",
  taipeiPumb: "北市抽水站",
  wasteFacility: "垃圾處理設施",
  wasteDisposalPoint: "垃圾投放點",
  wasteCleaningSquad: "清潔隊辦公點",
  agriPOI: "農業 POI",
  agriRuralRegen: "農村再生社區",
  agriSoil: "土壤分類",
  agriSoilFertility: "土壤肥力",
  agriLeisureFarmZones: "休閒農業區",
  agriCropSuitability: "作物適栽",
  agriRetail: "農產零售商",
  agriProduceWholesale: "蔬果批發商",
  agriWholesaleMarket: "農產批發市場",
  farmRoads: "農路",
  ecoNetworkZones: "國土綠網分區",
  forestryPolygon: "林業面 (polygon)",
  forestryLine: "林業線 (line)",
  forestryPOI: "林業點位 (POI)",
  hikingTrails: "步道",
  fireEvent: "火災事件",
  fireStation: "消防分隊",
  fireIsochrone: "救援等時圈",
  fireHydrant: "消防栓",
  livestockFarm: "畜禽飼養場",
  livestockSlaughter: "屠宰場",
  livestockFeed: "飼料廠",
  livestockMarket: "拍賣/批發市場",
  sportsVenue: "運動場館",
  medicalPOI: "醫療據點",
  medicalIsochrone: "醫療等時圈",
  satellite: "衛星",
  powerPlant: "電廠",
  osmSubstation: "變電所",
  osmPowerLine: "高壓輸電線",
  osmPowerTower: "高壓鐵塔",
  osmWindTurbine: "風機",
  osmSolarFarm: "光電廠",
  osmPowerPlantStatic: "OSM 電廠",
  offshoreWindZone: "離岸風電場址",
  islandPowerFacility: "離島電網設施",
  fossilFuelFacility: "化石燃料設施",
  geothermalWell: "地熱井",
  renewablePermitTaipei: "北市再生能源",
  evCharging: "電動車充電站",
  // 化石燃料 13 layer
  gasStationCpc: "加油站（中油）",
  gasStationFpcc: "加油站（台塑系）",
  gasStationTaisugar: "加油站（台糖）",
  gasStationOther: "加油站（其他 / 私營）",
  gasStationCanonical: "加油站 SSOT",
  lpgSubpackaging: "LPG 分裝 / 儲存場",
  lpgRetailers: "LPG 加氣站 / 瓦斯行",
  lngTerminal: "LNG 接收站",
  pipelineGas: "天然氣主幹線",
  pipelineOilGas: "油氣管線（OSM）",
  industrialRefinery: "煉油 / 化工廠",
  industrialStorageTank: "油氣儲槽",
  industrialPowerPlant: "火力廠 polygon",
  coalTerminal: "煤炭碼頭",
  // 雲林 POC 覆蓋分析
  gasCoverageAll: "加油站總覆蓋密度",
  gasCoverageCpc: "中油 30km 可達",
  gasCoverageFpcc: "台塑 30km 可達",
  gasCoverageTaisugar: "台糖 30km 可達",
  evIsland: "充電站 30km 孤島",
  lightningStrike: "落雷",
  nuclearStation: "核安觀測站",
  earthquakeGlobal: "全球地震 USGS",
  typhoonTrack: "颱風軌跡",
  climateField: "氣候場讀值",
  // Base map
  countyBoundary: "縣市界",
  townshipBoundary: "鄉鎮市區界",
  villageBoundary: "村里界",
  contour25k: "等高線 25k (10m)",
  contourDtm20: "等高線 DTM 20m",
  osmRoadDrive: "道路 (OSM)",
  osmExpressway: "快速道路 (OSM)",
  hillshade: "山體陰影",
  slope: "坡度",
  aspect: "坡向",
  // 警政司法民防
  policeStation: "警察機關",
  womenChildWarning: "婦幼警示點",
  speedCamera: "測速照相",
  speedZoneSegment: "區間測速路段",
  court: "法院",
  prosecutorsOffice: "檢察署",
  correctionalFacility: "矯正機關",
  courtJurisdiction: "法院管轄區",
  crimeAreaMonthly: "鄉鎮犯罪統計",
  theftTaoyuan: "桃園竊盜點",
  trafficAccidentYearly: "A1 死亡事故（年度）",
  accidentTaipei: "北市事故點",
  a1AccidentRealtime: "A1 即時事故",
  investigationBureau: "調查局",
  antiCorruptionOffice: "廉政署",
  immigrationOffice: "移民署服務站",
  coastGuardStation: "海巡",
  civilDefenseShelter: "防空避難所",
  aviationControl: "飛航情報/終端管制",
  aviationRestricted: "機場管制/限航/危險",
  droneNoFlyZone: "無人機禁航區",
  droneRestrictedZone: "無人機限航區",
  // 警察覆蓋分析
  policeIsoSubstation: "派出所等時圈",
  policeIsoPrecinct: "分局等時圈",
  policeIsoCityDept: "縣市警局等時圈",
  // AI 助手標記點
  chatHighlight: "地圖標記",
};
