import { useCallback, useRef, useState } from "react";
import type { LayerVisibility } from "../types";

export function useLayerVisibility() {
  const [layerVisibility, setLayerVisibility] = useState<LayerVisibility>({
    flights: true,
    ships: true,
    rail: true,
    stationsTHSR: true,
    stationsTRA: true,
    stationsMetro: true,
    ports: true,
    lighthouses: true,
    airports: true,
    highways: false,
    provincialRoads: false,
    cctv: false,
    etcGantry: false,
    serviceArea: false,
    serviceAreaPolygon: false,
    taxiStand: false,
    windPlan: false,
    busStationsCity: false,
    busStationsIntercity: false,
    bikeStations: false,
    cyclingRoutes: false,
    freewayCongestion: false,
    weatherStations: false,
    h3Population: false,
    popCount: false,
    indicators: false,
    socioeconomic: false,
    spatialEconomy: false,
    temperatureWave: false,
    schools: false,
    convenienceStores: false,
    submarineCables: false,
    landingStations: false,
    activeFaults: false,
    newsEvents: false,
    youbikeFullness: false,
    earthquakes: false,
    disasterAlerts: false,
    cwaCloudImagery: false,
    cwaRadarImagery: false,
    aqiImagery: false,
    aqiStations: false,
    aqiMicroSensors: false,
    busLive: false,
    busIntercityLive: false,
    waterBasins: false,
    waterRivers: false,
    waterLevees: false,
    waterCanals: false,
    waterProtectionZones: false,
    waterReservoirs: false,
    waterFacilities: false,
    waterMonitorStations: false,
    waterFloodExtreme: false,
    waterDetentionBasins: false,
    rainGauge: false,
    riverLevel: false,
    groundwater: false,
    groundwaterWells: false,
    iotWraRiver: false,
    iotWraStructure: false,
    fireEvents: false,
    fireLatest: false,
    fireStations: false,
    fireHydrants: false,
    agriculture: false,
    agriSoil: false,
    agriSoilFertility: false,
    agriLeisureFarmZones: false,
    agriRuralRegen: false,
    agriCropSuitability: false,
    agriPOI: false,
    wasteTruck: false,
    wasteSchedule: false,
    wasteScheduleNote: true,
    wasteStopsStatic: false,
    wasteRoute: false,
    wasteStop: false,
    wfIncinerator: false,
    wfLandfill: false,
    wfTransfer: false,
    wfMedical: false,
    wfMonitoring: false,
    wfRecycling: false,
    wfScrapYard: false,
    wfOther: false,
    wdClothes: false,
    wdMixed: false,
    wdRecyclingContainer: false,
    wdBattery: false,
  });
  const layerVisibilityRef = useRef(layerVisibility);
  layerVisibilityRef.current = layerVisibility;

  const toggleVisibility = useCallback((layer: keyof LayerVisibility) => {
    setLayerVisibility((prev) => ({ ...prev, [layer]: !prev[layer] }));
  }, []);

  return { layerVisibility, layerVisibilityRef, setLayerVisibility, toggleVisibility };
}
