import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { gunzipSync } from "node:zlib";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { civilDefenseSheltersOwnerAdapter, civilDefenseSheltersOwnerDescriptor } from "../civilDefenseSheltersOwnerDataset";
import { clearPointDatasetCache } from "../pointDatasetAdapter";
import { clearPointPartitionCache } from "../pointDatasetPartitions";
import { QueryExecutor } from "../queryExecutor";
const root = "../runtime/owner-only/civil-defense-shelters/", prefix = "/__local-research-owner-only/civil-defense-shelters/", sourcePath = "/Users/migu/Desktop/資料庫/gen_ai_try/ichef_工作用/GIS/taipei-gis-analytics/data/processed/police_justice/civil_defense_shelters/civil_defense_shelters_20260824.geojson";
type Bbox = readonly [number, number, number, number];
async function rawOracle(bbox: Bbox, precision: string): Promise<number> { const source = JSON.parse(await readFile(sourcePath, "utf8")) as { features: { geometry: { coordinates: [number, number] }; properties: { coord_precision: string } }[] }; return source.features.filter(feature => { const [lng, lat] = feature.geometry.coordinates; return lng >= bbox[0] && lng <= bbox[2] && lat >= bbox[1] && lat <= bbox[3] && feature.properties.coord_precision === precision; }).length; }
beforeEach(() => { clearPointDatasetCache(); clearPointPartitionCache(); vi.stubGlobal("fetch", vi.fn(async (url: string) => new Response(await readFile(`${root}${url.slice(prefix.length)}`), { headers: { "content-type": "application/geo+json" } }))); }); afterEach(() => { vi.unstubAllGlobals(); clearPointDatasetCache(); clearPointPartitionCache(); });
it("forces bbox and retains owner-only proxy semantics", async () => { const executor = new QueryExecutor([civilDefenseSheltersOwnerAdapter]); await expect(executor.execute({ datasetId: civilDefenseSheltersOwnerDescriptor.datasetId })).rejects.toThrow("BBOX_REQUIRED"); expect(civilDefenseSheltersOwnerDescriptor.geometry).toMatchObject({ role: "proxy", spatialAnalysisEligible: false }); expect(civilDefenseSheltersOwnerDescriptor.supportedOperations).not.toContain("nearest"); expect(civilDefenseSheltersOwnerDescriptor.fields.map(field => field.name)).not.toEqual(expect.arrayContaining(["address", "addr_norm", "confidence", "_provenance_sources"])); });
it.skipIf(!existsSync(`${root}manifest.json`))("reads immutable safe shard fields and retains coordinate-quality exclusions", async () => { const manifest = JSON.parse(await readFile(`${root}manifest.json`, "utf8")) as { shards: { path: string }[] }; const shard = JSON.parse(gunzipSync(await readFile(`${root}${manifest.shards[0]!.path}`)).toString("utf8")) as { features: { geometry: { coordinates: [number, number] }; properties: { entity_id: string; name: string } }[] }; const target = shard.features[0]!, [lng, lat] = target.geometry.coordinates; const result = await new QueryExecutor([civilDefenseSheltersOwnerAdapter]).execute({ datasetId: civilDefenseSheltersOwnerDescriptor.datasetId, bbox: [lng, lat, lng, lat], filters: [{ field: "entity_id", op: "eq", value: target.properties.entity_id }], limit: 100 }); expect(result.rows[0]).toMatchObject({ entity_id: target.properties.entity_id, name: target.properties.name, geometry: { type: "Point", coordinates: [lng, lat] } }); expect(result.excludedByReason).toMatchObject({ coord_suspect: 1753, coord_precision_street_block: 1843, coord_precision_approximate: 5871 }); });
it.skipIf(!existsSync(`${root}manifest.json`))("matches full-source new-location and coord_precision oracles with bounded reads", async () => { const cases: { bbox: Bbox; precision: string; expected: number }[] = [{ bbox: [121.50, 25.04, 121.54, 25.08], precision: "exact", expected: 6036 }, { bbox: [120.62, 24.12, 120.68, 24.16], precision: "approximate", expected: 2089 }]; const executor = new QueryExecutor([civilDefenseSheltersOwnerAdapter]); for (const item of cases) { const oracle = await rawOracle(item.bbox, item.precision); const result = await executor.execute({ datasetId: civilDefenseSheltersOwnerDescriptor.datasetId, bbox: item.bbox, filters: [{ field: "coord_precision", op: "eq", value: item.precision }], select: ["entity_id", "coord_precision", "geometry"], limit: 100 }); expect(oracle).toBe(item.expected); expect(result.totalMatched).toBe(oracle); expect(result.cost.rowsScanned).toBeLessThanOrEqual(20_000); expect(result.cost.bytesScanned).toBeLessThanOrEqual(8 * 1024 * 1024); } });
it.skipIf(!existsSync(`${root}manifest.json`))("fails closed when a broad bbox exceeds the partition byte budget", async () => { await expect(new QueryExecutor([civilDefenseSheltersOwnerAdapter]).execute({ datasetId: civilDefenseSheltersOwnerDescriptor.datasetId, bbox: [118, 21, 123, 27], limit: 1 })).rejects.toThrow("DATASET_TOO_LARGE"); });
