import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { clearPointDatasetCache } from "../pointDatasetAdapter";
import { culturalFacilitiesOwnerAdapter, culturalFacilitiesOwnerDescriptor } from "../culturalFacilitiesOwnerDataset";
import { QueryExecutor, type QueryFilter } from "../queryExecutor";

const source = "/Users/migu/Desktop/資料庫/gen_ai_try/ichef_工作用/GIS/taipei-gis-analytics/data/processed/culture/cultural_facilities_moc/cultural_facilities_moc_20260716.geojson";
const sidecar = "../runtime/owner-only/cultural-facilities/cultural-facilities-owner-20260716.geojson";
type Bbox = readonly [number, number, number, number];
beforeEach(() => { clearPointDatasetCache(); vi.stubGlobal("fetch", vi.fn(async () => new Response(await readFile(sidecar), { headers: { "content-type": "application/geo+json" } }))); });
afterEach(() => { vi.unstubAllGlobals(); clearPointDatasetCache(); });
async function oracle(bbox: Bbox, filters: readonly QueryFilter[] = []) { const collection = JSON.parse(await readFile(source, "utf8")) as { features: { geometry: { coordinates: [number, number] } | null; properties: Record<string, unknown> }[] }; return collection.features.filter(feature => { if (!feature.geometry) return false; const [lng, lat] = feature.geometry.coordinates; return lng >= bbox[0] && lng <= bbox[2] && lat >= bbox[1] && lat <= bbox[3] && filters.every(filter => feature.properties[filter.field] === filter.value); }).length; }
it.skipIf(!existsSync(sidecar))("matches independent Taipei and Kaohsiung point oracles", async () => { const executor = new QueryExecutor([culturalFacilitiesOwnerAdapter]); for (const bbox of [[121.5, 25.02, 121.58, 25.1], [120.25, 22.58, 120.35, 22.68]] as const) { const result = await executor.execute({ datasetId: culturalFacilitiesOwnerDescriptor.datasetId, bbox, select: ["facility_id", "facility_type", "coord_status", "geometry"], limit: 100 }); expect(result.totalMatched).toBe(await oracle(bbox)); expect(result.rows.every(row => (row.geometry as { type?: string } | null)?.type === "Point")).toBe(true); } });
it.skipIf(!existsSync(sidecar))("matches the category variant and retains no_coord only for attribute reads", async () => { const executor = new QueryExecutor([culturalFacilitiesOwnerAdapter]); const bbox: Bbox = [121.5, 25.02, 121.58, 25.1]; const filters: QueryFilter[] = [{ field: "facility_type", op: "eq", value: "實體書店" }]; const spatial = await executor.execute({ datasetId: culturalFacilitiesOwnerDescriptor.datasetId, bbox, filters, select: ["facility_id", "facility_type", "geometry"], limit: 100 }); expect(spatial.totalMatched).toBe(await oracle(bbox, filters)); const noCoord = await executor.execute({ datasetId: culturalFacilitiesOwnerDescriptor.datasetId, filters: [{ field: "coord_status", op: "eq", value: "no_coord" }], select: ["facility_id", "coord_status", "geometry"], limit: 1 }); expect(noCoord.totalMatched).toBe(383); expect(noCoord.rows[0]?.geometry).toBeNull(); expect(culturalFacilitiesOwnerDescriptor.geometry).toMatchObject({ role: "proxy", spatialAnalysisEligible: false }); expect(culturalFacilitiesOwnerDescriptor.supportedOperations).not.toContain("nearest"); });
