import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { clearPointDatasetCache } from "../pointDatasetAdapter";
import { QueryExecutor } from "../queryExecutor";
import { clearPointPartitionCache, fireHydrantsOwnerAdapter, fireHydrantsOwnerDescriptor } from "../fireHydrantsOwnerDataset";
const root = "../runtime/owner-only/fire-hydrants/"; const prefix = "/__local-research-owner-only/fire-hydrants/"; const sourcePath = "/Users/migu/Desktop/資料庫/gen_ai_try/ichef_工作用/GIS/taipei-gis-analytics/data/processed/fire/hydrants/hydrants.csv"; type Bbox = readonly [number, number, number, number];
function parseCsv(input: string): string[][] { const rows: string[][] = []; let row: string[] = [], value = "", quoted = false; for (let i = 0; i < input.length; i++) { const char = input[i]!; if (quoted) { if (char === '"' && input[i + 1] === '"') { value += '"'; i++; } else if (char === '"') quoted = false; else value += char; } else if (char === '"') quoted = true; else if (char === ",") { row.push(value); value = ""; } else if (char === "\n") { row.push(value.replace(/\r$/, "")); rows.push(row); row = []; value = ""; } else value += char; } if (row.length || value) { row.push(value); rows.push(row); } return rows; }
async function oracle(bbox: Bbox): Promise<number> { const [header, ...rows] = parseCsv((await readFile(sourcePath, "utf8")).toString().replace(/^\uFEFF/, "")); const lng = header!.indexOf("lng"), lat = header!.indexOf("lat"); return rows.filter(values => { const x = Number(values[lng]), y = Number(values[lat]); return x >= bbox[0] && x <= bbox[2] && y >= bbox[1] && y <= bbox[3]; }).length; }
beforeEach(() => { clearPointDatasetCache(); clearPointPartitionCache(); vi.stubGlobal("fetch", vi.fn(async (url: string) => new Response(await readFile(`${root}${url.slice(prefix.length)}`), { headers: { "content-type": "application/geo+json" } }))); }); afterEach(() => { vi.unstubAllGlobals(); clearPointDatasetCache(); clearPointPartitionCache(); });
it("requires bbox and documents only the A/E CSV snapshot", async () => { const executor = new QueryExecutor([fireHydrantsOwnerAdapter]); await expect(executor.execute({ datasetId: fireHydrantsOwnerDescriptor.datasetId })).rejects.toThrow("BBOX_REQUIRED"); expect(fireHydrantsOwnerDescriptor.geometry).toMatchObject({ role: "proxy", spatialAnalysisEligible: false }); expect(fireHydrantsOwnerDescriptor.coverage).toContain("not a four-county"); expect(fireHydrantsOwnerDescriptor.fields.map(field => field.name)).not.toContain("address"); });
it.skipIf(!existsSync(`${root}manifest.json`))("matches Taipei and dense Kaohsiung CSV oracles within bounded partitions", async () => { const executor = new QueryExecutor([fireHydrantsOwnerAdapter]); for (const [bbox, expected] of [[[121.54, 25.02, 121.57, 25.05], 2179], [[120.28, 22.61, 120.32, 22.65], 5275]] as const) { const result = await executor.execute({ datasetId: fireHydrantsOwnerDescriptor.datasetId, bbox, select: ["hydrant_id", "county_id", "hydrant_type", "data_source"], limit: 100 }); expect(await oracle(bbox)).toBe(expected); expect(result.totalMatched).toBe(expected); expect(result.cost.rowsScanned).toBeLessThanOrEqual(20_000); expect(result.cost.bytesScanned).toBeLessThanOrEqual(8 * 1024 * 1024); } });
it.skipIf(!existsSync(`${root}manifest.json`))("fails closed for a broad Taiwan bbox", async () => { await expect(new QueryExecutor([fireHydrantsOwnerAdapter]).execute({ datasetId: fireHydrantsOwnerDescriptor.datasetId, bbox: [118, 21.5, 122.5, 26.5], limit: 1 })).rejects.toThrow("DATASET_TOO_LARGE"); });
