import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { clearPointDatasetCache } from "../pointDatasetAdapter";
import { clearPointPartitionCache, livestockFarmsOwnerAdapters, livestockFarmsOwnerDescriptors } from "../livestockFarmsOwnerDatasets";
import { QueryExecutor } from "../queryExecutor";

const root = "../runtime/owner-only/livestock-farms/", prefix = "/__local-research-owner-only/livestock-farms/", sourcePath = "public/agriculture/livestock_farms.geojson";
const map = { "牛": "cattle", "雞": "chicken", "鴨": "duck", "鵝": "goose", "豬": "pig", "羊": "sheep" } as Record<string, string>;
type Bbox = readonly [number, number, number, number];
async function oracle(bbox: Bbox) { const source = JSON.parse(await readFile(sourcePath, "utf8")); const counts: Record<string, number> = { cattle: 0, chicken: 0, duck: 0, goose: 0, other: 0, pig: 0, sheep: 0 }; for (const feature of source.features) { const [lng, lat] = feature.geometry.coordinates; if (lng >= bbox[0] && lng <= bbox[2] && lat >= bbox[1] && lat <= bbox[3]) { const category = map[feature.properties["主畜種"]] ?? "other"; counts[category] = (counts[category] ?? 0) + 1; } } return counts; }
beforeEach(() => { clearPointDatasetCache(); clearPointPartitionCache(); vi.stubGlobal("fetch", vi.fn(async (url: string) => new Response(await readFile(`${root}${url.slice(prefix.length)}`), { headers: { "content-type": "application/geo+json" } }))); });
afterEach(() => { vi.unstubAllGlobals(); clearPointDatasetCache(); clearPointPartitionCache(); });
it("binds seven datasets one-to-one to pending livestock layerRefs without nearest or aggregate", () => { expect(livestockFarmsOwnerDescriptors.map(x => x.layerRefs[0])).toEqual(["livestockFarmCattle", "livestockFarmChicken", "livestockFarmDuck", "livestockFarmGoose", "livestockFarmOther", "livestockFarmPig", "livestockFarmSheep"]); for (const descriptor of livestockFarmsOwnerDescriptors) { expect(descriptor.geometry).toMatchObject({ role: "proxy", spatialAnalysisEligible: false }); expect(descriptor.supportedOperations).toEqual(["query_records"]); expect(descriptor.fields.map(x => x.name)).not.toContain("場名"); } });
it.skipIf(!existsSync(sourcePath))("matches full-source category oracles in Chiayi and Pingtung", async () => { const executor = new QueryExecutor(livestockFarmsOwnerAdapters); for (const [bbox, expected] of [[[120.30, 23.35, 120.55, 23.60], { cattle: 24, chicken: 331, duck: 73, goose: 34, other: 13, pig: 146, sheep: 27 }], [[120.40, 22.40, 120.75, 22.75], { cattle: 88, chicken: 543, duck: 269, goose: 52, other: 12, pig: 916, sheep: 64 }]] as const) { expect(await oracle(bbox)).toEqual(expected); for (const adapter of livestockFarmsOwnerAdapters) { const category = adapter.descriptor.datasetId.match(/farms-(.+)-owner/)![1]!; const result = await executor.execute({ datasetId: adapter.descriptor.datasetId, bbox, select: ["animal_category", "coordinate_source", "coordinate_precision"], limit: 100 }); expect(result.totalMatched).toBe((expected as Record<string, number>)[category]); expect(result.rows.every(row => row.animal_category === category)).toBe(true); expect(result.cost.rowsScanned).toBeLessThanOrEqual(5000); } } });
it.skipIf(!existsSync(`${root}manifest.json`))("requires bbox and fails closed when broad selection exceeds the owner-only scan budget", async () => { const executor = new QueryExecutor(livestockFarmsOwnerAdapters); await expect(executor.execute({ datasetId: livestockFarmsOwnerDescriptors[0]!.datasetId })).rejects.toThrow("BBOX_REQUIRED"); await expect(executor.execute({ datasetId: livestockFarmsOwnerDescriptors[0]!.datasetId, bbox: [118, 21.5, 122.5, 26.5], limit: 1 })).rejects.toThrow("DATASET_TOO_LARGE"); });
