import { existsSync } from "node:fs";
import { readFile } from "node:fs/promises";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { clearPointDatasetCache } from "../pointDatasetAdapter";
import { QueryExecutor } from "../queryExecutor";
import { lpgRetailersOwnerAdapter, lpgRetailersOwnerDescriptor, lpgSubpackagingOwnerAdapter, lpgSubpackagingOwnerDescriptor } from "../lpgOwnerDatasets";

const root = "../runtime/owner-only/lpg/";
const prefix = "/__local-research-owner-only/lpg/";
const processed = "/Users/migu/Desktop/資料庫/gen_ai_try/ichef_工作用/GIS/taipei-gis-analytics/data/processed/energy/lpg_facilities_canonical/lpg_facilities_canonical_20260620.geojson";
const bbox = [120.42, 23.45, 120.5, 23.51] as const;
beforeEach(() => { clearPointDatasetCache(); vi.stubGlobal("fetch", vi.fn(async (url: string) => new Response(await readFile(`${root}${url.slice(prefix.length)}`), { headers: { "content-type": "application/geo+json" } }))); });
afterEach(() => { vi.unstubAllGlobals(); clearPointDatasetCache(); });
async function oracle(kinds: readonly string[]) { const raw = JSON.parse(await readFile(processed, "utf8")) as { features: { geometry: { coordinates: [number, number] }; properties: { facility_kinds: string[] } }[] }; return raw.features.filter(feature => feature.properties.facility_kinds.some(kind => kinds.includes(kind)) && feature.geometry.coordinates[0] >= bbox[0] && feature.geometry.coordinates[0] <= bbox[2] && feature.geometry.coordinates[1] >= bbox[1] && feature.geometry.coordinates[1] <= bbox[3]).length; }
it.skipIf(!existsSync(`${root}lpg-subpackaging-owner-20260620.geojson`))("keeps the verified category subsets and a new-place bbox oracle", async () => { const executor = new QueryExecutor([lpgSubpackagingOwnerAdapter, lpgRetailersOwnerAdapter]); const sub = await executor.execute({ datasetId: lpgSubpackagingOwnerDescriptor.datasetId, bbox, select: ["name", "is_subpackaging", "geometry"], limit: 100 }); const retail = await executor.execute({ datasetId: lpgRetailersOwnerDescriptor.datasetId, bbox, select: ["name", "is_retailer", "is_cstation", "is_dealer", "geometry"], limit: 100 }); expect(sub.totalMatched).toBe(await oracle(["subpackaging"])); expect(retail.totalMatched).toBe(await oracle(["retailer", "cstation", "dealer"])); expect(sub.totalMatched).toBe(2); expect(retail.totalMatched).toBe(40); expect(sub.rows.every(row => row.is_subpackaging === true)).toBe(true); expect(retail.rows.every(row => row.is_retailer === true || row.is_cstation === true || row.is_dealer === true)).toBe(true); });
it.skipIf(!existsSync(`${root}lpg-retailers-owner-20260620.geojson`))("has no raw address provenance and holds rights and nearest claims", async () => { const executor = new QueryExecutor([lpgSubpackagingOwnerAdapter, lpgRetailersOwnerAdapter]); const dealers = await executor.execute({ datasetId: lpgRetailersOwnerDescriptor.datasetId, filters: [{ field: "is_dealer", op: "eq", value: true }], select: ["entity_id", "is_dealer"], limit: 100 }); expect(dealers.totalMatched).toBe(6); expect(lpgRetailersOwnerDescriptor.fields.map(field => field.name)).not.toEqual(expect.arrayContaining(["_provenance", "aliases", "source_url", "address", "phone", "name_raw"])); expect(lpgSubpackagingOwnerDescriptor.license).toContain("RIGHTS_HOLD"); expect(lpgRetailersOwnerDescriptor.geometry).toMatchObject({ role: "proxy", spatialAnalysisEligible: false }); expect(lpgRetailersOwnerDescriptor.supportedOperations).not.toContain("nearest"); });
