import { readFile } from "node:fs/promises";
import { afterEach, beforeEach, expect, it, vi } from "vitest";
import { streetTreesNationalOwnerAdapter, streetTreesNationalOwnerDescriptor } from "../streetTreesNationalOwnerDataset";
import { clearPointDatasetCache } from "../pointDatasetAdapter";
import { clearPointPartitionCache } from "../pointDatasetPartitions";
import { QueryExecutor } from "../queryExecutor";
const runtimeRoot = "../runtime/owner-only/street-trees-national/", urlPrefix = "/__local-research-owner-only/street-trees-national/";
const source = "/Users/migu/Desktop/資料庫/gen_ai_try/ichef_工作用/GIS/taipei-gis-analytics/data/processed/urban_open_space/street_trees_national/street_trees_national_20260714.geojson";
type Bbox = readonly [number, number, number, number];
async function oracle(bbox: Bbox) { const collection = JSON.parse(await readFile(source, "utf8")) as { features: { geometry: { coordinates: [number, number] }; properties: { location_type: string } }[] }; return collection.features.filter(feature => { const [lng, lat] = feature.geometry.coordinates; return lng >= bbox[0] && lng <= bbox[2] && lat >= bbox[1] && lat <= bbox[3]; }); }
beforeEach(() => { clearPointDatasetCache(); clearPointPartitionCache(); vi.stubGlobal("fetch", vi.fn(async (url: string) => new Response(await readFile(`${runtimeRoot}${url.slice(urlPrefix.length)}`), { headers: { "content-type": "application/geo+json" } }))); });
afterEach(() => { vi.unstubAllGlobals(); clearPointDatasetCache(); clearPointPartitionCache(); });
it("requires bbox and exposes safe proxy fields only", async () => { const executor = new QueryExecutor([streetTreesNationalOwnerAdapter]); await expect(executor.execute({ datasetId: streetTreesNationalOwnerDescriptor.datasetId })).rejects.toThrow("BBOX_REQUIRED"); expect(streetTreesNationalOwnerDescriptor.geometry).toMatchObject({ role: "proxy", spatialAnalysisEligible: false }); expect(streetTreesNationalOwnerDescriptor.supportedOperations).not.toContain("nearest"); expect(streetTreesNationalOwnerDescriptor.fields.map(field => field.name)).not.toEqual(expect.arrayContaining(["address", "lat", "lon"])); });
it("matches full-source Taipei and Taichung oracles and distinguishes Taichung park trees", async () => { const executor = new QueryExecutor([streetTreesNationalOwnerAdapter]); const taipei: Bbox = [121.50, 25.03, 121.51, 25.04], taichung: Bbox = [120.65, 24.16, 120.66, 24.17]; expect((await oracle(taipei)).length).toBe(1187); const taipeiResult = await executor.execute({ datasetId: streetTreesNationalOwnerDescriptor.datasetId, bbox: taipei, select: ["city"], limit: 100 }); expect(taipeiResult.totalMatched).toBe(1187); expect((await oracle(taichung)).length).toBe(701); const sidewalk = await executor.execute({ datasetId: streetTreesNationalOwnerDescriptor.datasetId, bbox: taichung, filters: [{ field: "location_type", op: "eq", value: "人行道" }], select: ["location_type"], limit: 100 }); const park = await executor.execute({ datasetId: streetTreesNationalOwnerDescriptor.datasetId, bbox: taichung, filters: [{ field: "location_type", op: "eq", value: "公園廣場" }], select: ["location_type"], limit: 100 }); expect(sidewalk.totalMatched).toBe(385); expect(park.totalMatched).toBe(316); expect(sidewalk.cost.rowsScanned).toBeLessThanOrEqual(20_000); expect(park.cost.bytesScanned).toBeLessThanOrEqual(8 * 1024 * 1024); });
it("fails closed for country-scale bbox", async () => { await expect(new QueryExecutor([streetTreesNationalOwnerAdapter]).execute({ datasetId: streetTreesNationalOwnerDescriptor.datasetId, bbox: [118, 21, 124, 27], limit: 1 })).rejects.toThrow("DATASET_TOO_LARGE"); });
