// ══════════════════════════════════════════════════════════════════
//  Upstream Registry — pulse layer ↔ taipei-gis-analytics catalog dataset
// ══════════════════════════════════════════════════════════════════
//
// Generated by scripts/audit/06_apply_to_pulse.py from match_final.csv.
// SSOT for upstream data sources is taipei-gis-analytics/docs/data-catalog/
// This file is the bridge: layer_key → catalog dataset_id.
//
// Status values:
//   verified         — bridged to one or more catalog datasets
//   pulse_only       — pure-frontend layer (derived / animated / no upstream)
//   catalog_missing  — needs new entry in catalog before bridging

import type { LayerVisibility } from '../types';
import { manifestUpstream, type ManifestKey } from './layerManifest';

export type UpstreamStatus = 'verified' | 'pulse_only' | 'catalog_missing';
export type UpstreamConfidence = 'HIGH' | 'MED' | 'LOW';

export interface UpstreamDataset {
  /** catalog dataset_id (matches frontmatter in taipei-gis-analytics/docs/data-catalog/<theme>/<dataset_id>.md) */
  datasetId: string;
  /** match confidence — HIGH = explicit frontend_target / exact name; MED = normalized variant; LOW = fuzzy */
  confidence: UpstreamConfidence;
}

/** Type of derivation for pulse_only layers. Extendable — add new kinds as compound
 *  analyses emerge (e.g. 'ratio' for A/B, 'temporal_diff' for time-series delta). */
export type DerivationType =
  | 'isochrone'         // OSRM 路網等時圈
  | 'coverage'          // 最近距離覆蓋分析（PMTiles 分級）
  | 'inverse'           // 反演（例：等時圈 → 沙漠）
  | 'aggregate'         // 聚合（例：多品牌 → 全體）
  | 'ratio'             // 比值（例：供需比）— 未來複合分析用
  | 'intersect'         // 空間交集（例：災害 × 人口）— 未來複合分析用
  | 'temporal_diff'     // 時序差分 — 未來
  | 'custom';           // 其他自訂

export interface UpstreamRef {
  status: UpstreamStatus;
  /** Primary catalog datasets (empty array for pulse_only / catalog_missing) */
  datasets: UpstreamDataset[];

  // ── Lineage fields (only meaningful when status='pulse_only') ──
  /** Pulse layer_keys this is derived from. Transitively yields upstream datasets via UPSTREAM_REGISTRY lookup. */
  derivedFromLayers?: string[];
  /** Catalog dataset_ids used directly (for compound analyses that bypass a pulse layer). */
  derivedFromDatasets?: string[];
  /** Classification of the derivation operation — for UI grouping and future-proofing compound analyses. */
  derivationType?: DerivationType;
  /** Short human-readable description of how the data is generated/processed. */
  processing?: string;

  /** Free-form reason when status != 'verified' */
  note?: string;
}

/**
 * 手寫血緣殘量 —— **AR-22 Phase 2 完成後為空**（348/348 全部由 layerManifest 派生）。
 * `Omit<…, ManifestKey>` 退化成 `{}` 的護欄語意說明見 layerCatalog 的
 * HANDWRITTEN_LAYER_COLORS。
 *
 * ⚠️ 衍生型血緣（`derivedFromLayers` / `derivationType` / `processing`）在 manifest
 * 的 `upstream` 欄位是**整包照抄**的，不是只有 status + datasets ——
 * 只抄前兩欄會靜默丟掉「這層是本站自己從別的 layer 算出來的」這件事
 * （gasCoverageAll / evIsland / 各 isochrone 覆蓋層）。
 */
const HANDWRITTEN_UPSTREAM: Omit<Record<keyof LayerVisibility, UpstreamRef>, ManifestKey> = {
  // （空 —— Phase 2 全數搬完）
};

/**
 * 血緣全集 —— 手寫殘量 + manifest 派生。
 * 型別維持 `Record<keyof LayerVisibility, UpstreamRef>`（tsc 護欄不弱化）。
 */
export const UPSTREAM_REGISTRY: Record<keyof LayerVisibility, UpstreamRef> = {
  ...HANDWRITTEN_UPSTREAM,
  ...manifestUpstream(),
};

// ── Convenience helpers ──

export function getUpstreamFor(layerKey: keyof LayerVisibility): UpstreamRef {
  return UPSTREAM_REGISTRY[layerKey];
}

export function getAllVerifiedDatasets(): Set<string> {
  const out = new Set<string>();
  for (const ref of Object.values(UPSTREAM_REGISTRY)) {
    if (ref.status === 'verified') {
      for (const d of ref.datasets) out.add(d.datasetId);
    }
  }
  return out;
}

/** Resolve upstream catalog dataset_ids for any layer (verified or pulse_only).
 *  For pulse_only: transitively walk derivedFromLayers + include derivedFromDatasets.
 *  Cycle-safe via visited set. */
export function resolveUpstreamDatasets(
  layerKey: keyof LayerVisibility,
  visited: Set<string> = new Set()
): string[] {
  if (visited.has(layerKey)) return [];
  visited.add(layerKey);
  const ref = UPSTREAM_REGISTRY[layerKey];
  if (!ref) return [];
  const out = new Set<string>();
  for (const d of ref.datasets) out.add(d.datasetId);
  for (const d of ref.derivedFromDatasets ?? []) out.add(d);
  for (const l of ref.derivedFromLayers ?? []) {
    for (const d of resolveUpstreamDatasets(l as keyof LayerVisibility, visited)) out.add(d);
  }
  return [...out];
}
