// ══════════════════════════════════════════════════════════════════
//  Upstream Registry — pulse layer ↔ taipei-gis-analytics catalog dataset
// ══════════════════════════════════════════════════════════════════
//
// Generated by scripts/audit/06_apply_to_pulse.py from match_final.csv.
// SSOT for upstream data sources is taipei-gis-analytics/docs/data-catalog/
// This file is the bridge: layer_key → catalog dataset_id.
//
// Status values:
//   verified         — bridged to one or more catalog datasets
//   pulse_only       — pure-frontend layer (derived / animated / no upstream)
//   catalog_missing  — needs new entry in catalog before bridging

import type { LayerVisibility } from '../types';

export type UpstreamStatus = 'verified' | 'pulse_only' | 'catalog_missing';
export type UpstreamConfidence = 'HIGH' | 'MED' | 'LOW';

export interface UpstreamDataset {
  /** catalog dataset_id (matches frontmatter in taipei-gis-analytics/docs/data-catalog/<theme>/<dataset_id>.md) */
  datasetId: string;
  /** match confidence — HIGH = explicit frontend_target / exact name; MED = normalized variant; LOW = fuzzy */
  confidence: UpstreamConfidence;
}

/** Type of derivation for pulse_only layers. Extendable — add new kinds as compound
 *  analyses emerge (e.g. 'ratio' for A/B, 'temporal_diff' for time-series delta). */
export type DerivationType =
  | 'isochrone'         // OSRM 路網等時圈
  | 'coverage'          // 最近距離覆蓋分析（PMTiles 分級）
  | 'inverse'           // 反演（例：等時圈 → 沙漠）
  | 'aggregate'         // 聚合（例：多品牌 → 全體）
  | 'ratio'             // 比值（例：供需比）— 未來複合分析用
  | 'intersect'         // 空間交集（例：災害 × 人口）— 未來複合分析用
  | 'temporal_diff'     // 時序差分 — 未來
  | 'custom';           // 其他自訂

export interface UpstreamRef {
  status: UpstreamStatus;
  /** Primary catalog datasets (empty array for pulse_only / catalog_missing) */
  datasets: UpstreamDataset[];

  // ── Lineage fields (only meaningful when status='pulse_only') ──
  /** Pulse layer_keys this is derived from. Transitively yields upstream datasets via UPSTREAM_REGISTRY lookup. */
  derivedFromLayers?: string[];
  /** Catalog dataset_ids used directly (for compound analyses that bypass a pulse layer). */
  derivedFromDatasets?: string[];
  /** Classification of the derivation operation — for UI grouping and future-proofing compound analyses. */
  derivationType?: DerivationType;
  /** Short human-readable description of how the data is generated/processed. */
  processing?: string;

  /** Free-form reason when status != 'verified' */
  note?: string;
}

export const UPSTREAM_REGISTRY: Record<keyof LayerVisibility, UpstreamRef> = {
  countyBoundary: {
    status: 'verified',
    datasets: [{ datasetId: 'county_boundary', confidence: 'MED' }],
  },
  townshipBoundary: {
    status: 'verified',
    datasets: [{ datasetId: 'township_boundary', confidence: 'MED' }],
  },
  villageBoundary: {
    status: 'verified',
    datasets: [{ datasetId: 'village_boundary', confidence: 'MED' }],
  },
  contour25k: {
    status: 'verified',
    datasets: [{ datasetId: 'contour_25k', confidence: 'MED' }],
  },
  contourDtm20: {
    status: 'verified',
    datasets: [{ datasetId: 'contour_dtm20', confidence: 'MED' }],
  },
  hillshade: {
    status: 'verified',
    datasets: [{ datasetId: 'hillshade', confidence: 'MED' }],
  },
  slope: {
    status: 'verified',
    datasets: [{ datasetId: 'slope', confidence: 'MED' }],
  },
  aspect: {
    status: 'verified',
    datasets: [{ datasetId: 'aspect', confidence: 'MED' }],
  },
  osmRoadDrive: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_road_drive', confidence: 'MED' }],
  },
  flights: {
    status: 'verified',
    datasets: [{ datasetId: 'opensky_flights', confidence: 'HIGH' }],
  },
  ships: {
    status: 'verified',
    datasets: [{ datasetId: 'ship', confidence: 'HIGH' }],
  },
  rail: {
    status: 'verified',
    datasets: [{ datasetId: 'rail', confidence: 'MED' }],
  },
  busLive: {
    status: 'verified',
    datasets: [{ datasetId: 'bus_realtime', confidence: 'HIGH' }],
  },
  busIntercityLive: {
    status: 'verified',
    datasets: [{ datasetId: 'bus_realtime', confidence: 'HIGH' }],
  },
  touristShuttleLive: {
    status: 'verified',
    datasets: [{ datasetId: 'bus_realtime', confidence: 'HIGH' }],
  },
  stationsTHSR: {
    status: 'verified',
    datasets: [{ datasetId: 'rail_stations', confidence: 'MED' }],
  },
  stationsTRA: {
    status: 'verified',
    datasets: [{ datasetId: 'rail_stations', confidence: 'MED' }],
  },
  stationsMetro: {
    status: 'verified',
    datasets: [{ datasetId: 'rail_stations', confidence: 'MED' }],
  },
  busStationsCity: {
    status: 'verified',
    datasets: [{ datasetId: 'bus', confidence: 'LOW' }],
  },
  busStationsIntercity: {
    status: 'verified',
    datasets: [{ datasetId: 'bus', confidence: 'LOW' }],
  },
  bikeStations: {
    status: 'verified',
    datasets: [{ datasetId: 'bike', confidence: 'MED' }],
  },
  highways: {
    status: 'verified',
    datasets: [{ datasetId: 'freeway', confidence: 'MED' }],
  },
  osmExpressway: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_expressway', confidence: 'MED' }],
  },
  provincialRoads: {
    status: 'verified',
    datasets: [{ datasetId: 'road', confidence: 'MED' }],
  },
  cyclingRoutes: {
    status: 'verified',
    datasets: [{ datasetId: 'bike', confidence: 'MED' }],
  },
  cctv: {
    status: 'verified',
    datasets: [{ datasetId: 'cctv', confidence: 'MED' }],
  },
  etcGantry: {
    status: 'verified',
    datasets: [{ datasetId: 'etc_gantry', confidence: 'MED' }],
  },
  serviceArea: {
    status: 'verified',
    datasets: [{ datasetId: 'service_area', confidence: 'MED' }],
  },
  serviceAreaPolygon: {
    status: 'verified',
    datasets: [{ datasetId: 'service_area_polygon', confidence: 'MED' }],
  },
  taxiStand: {
    status: 'verified',
    datasets: [{ datasetId: 'taxi_stand', confidence: 'MED' }],
  },
  ports: {
    status: 'verified',
    datasets: [{ datasetId: 'ports', confidence: 'MED' }],
  },
  airports: {
    status: 'verified',
    datasets: [{ datasetId: 'airport', confidence: 'HIGH' }],
  },
  lighthouses: {
    status: 'verified',
    datasets: [{ datasetId: 'light_house', confidence: 'HIGH' }],
  },
  aviationControl: {
    status: 'verified',
    datasets: [{ datasetId: 'airspace_aip', confidence: 'LOW' }],
  },
  aviationRestricted: {
    status: 'verified',
    datasets: [{ datasetId: 'airport_safety_zones', confidence: 'LOW' }],
  },
  droneNoFlyZone: {
    status: 'verified',
    datasets: [{ datasetId: 'airport_safety_zones', confidence: 'LOW' }],
  },
  droneRestrictedZone: {
    status: 'verified',
    datasets: [{ datasetId: 'drone_restricted_zones', confidence: 'HIGH' }],
  },
  freewayCongestion: {
    status: 'verified',
    datasets: [{ datasetId: 'road_congestion', confidence: 'HIGH' }],
  },
  roadEvents: {
    status: 'verified',
    datasets: [{ datasetId: 'road_event', confidence: 'HIGH' }],
  },
  popCount: {
    status: 'verified',
    datasets: [{ datasetId: 'population', confidence: 'MED' }],
  },
  h3Population: {
    status: 'verified',
    datasets: [{ datasetId: 'population', confidence: 'MED' }],
  },
  indicators: {
    status: 'verified',
    datasets: [{ datasetId: 'county_indicators_yearly', confidence: 'MED' }],
  },
  socioeconomic: {
    status: 'verified',
    datasets: [{ datasetId: 'village_comprehensive_extended', confidence: 'LOW' }],
  },
  spatialEconomy: {
    status: 'verified',
    datasets: [{ datasetId: 'village_comprehensive_extended', confidence: 'LOW' }],
  },
  youbikeFullness: {
    status: 'verified',
    datasets: [{ datasetId: 'youbike_baselines', confidence: 'HIGH' }],
  },
  weatherStations: {
    status: 'verified',
    datasets: [{ datasetId: 'weather', confidence: 'HIGH' }],
  },
  cwaCloudImagery: {
    status: 'verified',
    datasets: [{ datasetId: 'cwa_satellite', confidence: 'HIGH' }],
  },
  cwaRadarImagery: {
    status: 'verified',
    datasets: [{ datasetId: 'cwa_satellite', confidence: 'HIGH' }],
  },
  temperatureWave: {
    status: 'verified',
    datasets: [{ datasetId: 'weather', confidence: 'MED' }],
  },
  aqiImagery: {
    status: 'verified',
    datasets: [{ datasetId: 'air_quality', confidence: 'MED' }],
  },
  aqiStations: {
    status: 'verified',
    datasets: [{ datasetId: 'air_quality', confidence: 'HIGH' }],
  },
  aqiMicroSensors: {
    status: 'verified',
    datasets: [{ datasetId: 'air_quality', confidence: 'HIGH' }],
  },
  waterFacilities: {
    status: 'verified',
    datasets: [{ datasetId: 'water_facilities_osm', confidence: 'MED' }],
  },
  waterMonitorStations: {
    status: 'verified',
    datasets: [{ datasetId: 'rain_gauge_stations', confidence: 'LOW' }],
  },
  waterReservoirs: {
    status: 'verified',
    datasets: [{ datasetId: 'reservoir_storage_wra', confidence: 'HIGH' }],
  },
  groundwaterWells: {
    status: 'verified',
    datasets: [{ datasetId: 'groundwater_wells', confidence: 'MED' }],
  },
  rainGauge: {
    status: 'verified',
    datasets: [{ datasetId: 'rain_gauge_stations', confidence: 'MED' }],
  },
  riverLevel: {
    status: 'verified',
    datasets: [{ datasetId: 'river_level_stations_wra', confidence: 'MED' }],
  },
  floodSensor: {
    status: 'verified',
    datasets: [{ datasetId: 'water.uswg_measurements', confidence: 'HIGH' }],
  },
  iotWraRiver: {
    status: 'verified',
    datasets: [{ datasetId: 'river_water_level_realtime', confidence: 'MED' }],
  },
  iotWraStructure: {
    status: 'verified',
    datasets: [{ datasetId: 'dam_weirs_wra', confidence: 'MED' }],
  },
  taipeiSewer: {
    status: 'verified',
    datasets: [{ datasetId: 'storm_drainage_pipes', confidence: 'MED' }],
  },
  taipeiEvacuate: {
    status: 'verified',
    datasets: [{ datasetId: 'civil_defense_shelters', confidence: 'MED' }],
  },
  taipeiPumb: {
    status: 'verified',
    datasets: [{ datasetId: 'pump_stations_wra', confidence: 'HIGH' }],
  },
  waterBasins: {
    status: 'verified',
    datasets: [{ datasetId: 'river_basins_wra', confidence: 'HIGH' }],
  },
  waterRivers: {
    status: 'verified',
    datasets: [{ datasetId: 'river_polygons_wra', confidence: 'HIGH' }],
  },
  waterLevees: {
    status: 'verified',
    datasets: [{ datasetId: 'river_levees_wra', confidence: 'HIGH' }],
  },
  waterCanals: {
    status: 'verified',
    datasets: [{ datasetId: 'irrigation_canals', confidence: 'HIGH' }],
  },
  waterProtectionZones: {
    status: 'verified',
    datasets: [{ datasetId: 'water_zones_wra', confidence: 'HIGH' }],
  },
  waterDetentionBasins: {
    status: 'verified',
    datasets: [{ datasetId: 'detention_basins', confidence: 'MED' }],
  },
  groundwater: {
    status: 'verified',
    datasets: [{ datasetId: 'groundwater_wells', confidence: 'HIGH' }],
  },
  waterFloodExtreme: {
    status: 'verified',
    datasets: [{ datasetId: 'flood_hazard_wra', confidence: 'MED' }],
  },
  floodSensorIsochrone: {
    status: 'verified',
    datasets: [{ datasetId: 'water.uswg_measurements', confidence: 'LOW' }],
  },
  precipRaster: {
    status: 'verified',
    datasets: [{ datasetId: 'water.precipitation_raster_frames', confidence: 'HIGH' }],
  },
  lifelineAlerts: {
    status: 'verified',
    datasets: [{ datasetId: 'ncdr_alerts', confidence: 'HIGH' }],
  },
  floodAlerts: {
    status: 'verified',
    datasets: [{ datasetId: 'ncdr_alerts', confidence: 'HIGH' }],
  },
  weatherAlerts: {
    status: 'verified',
    datasets: [{ datasetId: 'ncdr_alerts', confidence: 'HIGH' }],
  },
  transitAlerts: {
    status: 'verified',
    datasets: [{ datasetId: 'ncdr_alerts', confidence: 'HIGH' }],
  },
  safetyAlerts: {
    status: 'verified',
    datasets: [{ datasetId: 'ncdr_alerts', confidence: 'HIGH' }],
  },
  earthquakes: {
    status: 'verified',
    datasets: [{ datasetId: 'earthquake', confidence: 'HIGH' }],
  },
  activeFaults: {
    status: 'verified',
    datasets: [{ datasetId: 'earthquake', confidence: 'LOW' }],
  },
  lightning: {
    status: 'verified',
    datasets: [{ datasetId: 'lightning_taipower', confidence: 'HIGH' }],
  },
  nuclearRadiation: {
    status: 'verified',
    datasets: [{ datasetId: 'nuclear_radiation_taipower', confidence: 'HIGH' }],
  },
  earthquakesGlobal: {
    status: 'verified',
    datasets: [{ datasetId: 'usgs_earthquakes_global', confidence: 'HIGH' }],
  },
  typhoonTracks: {
    status: 'verified',
    datasets: [{ datasetId: 'jma_typhoon_positions', confidence: 'HIGH' }],
  },
  windField: {
    status: 'verified',
    datasets: [{ datasetId: 'noaa_gfs_wind_forecast', confidence: 'MED' }],
  },
  oceanCurrents: {
    status: 'verified',
    datasets: [{ datasetId: 'cmems_ocean_forecast', confidence: 'LOW' }],
  },
  dustForecast: {
    status: 'verified',
    datasets: [{ datasetId: 'cams_atmosphere_forecast', confidence: 'LOW' }],
  },
  fireStations: {
    status: 'verified',
    datasets: [{ datasetId: 'fire_stations', confidence: 'MED' }],
  },
  fireHydrants: {
    status: 'verified',
    datasets: [{ datasetId: 'fire_hydrants', confidence: 'MED' }],
  },
  fireEvents: {
    status: 'verified',
    datasets: [{ datasetId: 'fire_incidents', confidence: 'HIGH' }],
  },
  fireLatest: {
    status: 'verified',
    datasets: [{ datasetId: 'fire_incidents', confidence: 'HIGH' }],
  },
  fireIsochrone: {
    status: 'pulse_only',
    datasets: [],
    derivedFromLayers: ['fireStations'],
    derivationType: 'isochrone',
    processing: 'OSRM 路網等時圈計算（救援抵達 ≤ 5/8/10 分鐘）— 從消防分隊出發',
    note: 'FIX: 派生分析：消防分隊 + 路網救援等時圈',
  },
  medHospital: {
    status: 'verified',
    datasets: [{ datasetId: 'medical', confidence: 'MED' }],
  },
  medClinic: {
    status: 'verified',
    datasets: [{ datasetId: 'medical', confidence: 'MED' }],
  },
  medPharmacy: {
    status: 'verified',
    datasets: [{ datasetId: 'medical', confidence: 'MED' }],
  },
  medAED: {
    status: 'verified',
    datasets: [{ datasetId: 'aed', confidence: 'HIGH' }],
  },
  medLTC: {
    status: 'verified',
    datasets: [{ datasetId: 'long_term_care', confidence: 'HIGH' }],
  },
  medIsochrone: {
    status: 'pulse_only',
    datasets: [],
    derivedFromLayers: ['medHospital', 'medClinic'],
    derivationType: 'isochrone',
    processing: 'OSRM 路網等時圈計算（駕車時間 5/10/15/30 分鐘）— 從醫療 POI 出發沿實際路網擴散',
    note: 'FIX: 派生分析：醫療 POI + 路網等時圈計算結果',
  },
  medDesert: {
    status: 'pulse_only',
    datasets: [],
    derivedFromLayers: ['medIsochrone'],
    derivationType: 'inverse',
    processing: '等時圈反演 — 距任一醫療設施駕車 > 30 分鐘的村里標為醫療沙漠',
    note: 'FIX: 派生分析：等時圈反演的醫療沙漠',
  },
  erHospital: {
    status: 'pulse_only',
    datasets: [],
    note: '即時急診壅塞 RPC（get_er_hospital_latest / 24h，realtime.er_hospital_status）已 apply 到 production；座標 join medical geojson。catalog dataset 條目待補（handoff pending）',
  },
  agriPOI: {
    status: 'verified',
    datasets: [{ datasetId: 'agritourism_certified_2024', confidence: 'MED' }],
  },
  agriRetail: {
    status: 'verified',
    datasets: [{ datasetId: 'agri_retail_companies', confidence: 'HIGH' }],
  },
  agriProduceWholesale: {
    status: 'verified',
    datasets: [{ datasetId: 'produce_wholesale_companies', confidence: 'HIGH' }],
  },
  agriWholesaleMarket: {
    status: 'verified',
    datasets: [{ datasetId: 'agri_wholesale_market_companies', confidence: 'HIGH' }],
  },
  // 🐷 畜牧 — 飼養場 4 層共用 livestock_farms dataset（filter 分畜種）
  livestockFarmPig: { status: 'verified', datasets: [{ datasetId: 'livestock_farms', confidence: 'MED' }] },
  livestockFarmChicken: { status: 'verified', datasets: [{ datasetId: 'livestock_farms', confidence: 'MED' }] },
  livestockFarmCattle: { status: 'verified', datasets: [{ datasetId: 'livestock_farms', confidence: 'MED' }] },
  livestockFarmDuck: { status: 'verified', datasets: [{ datasetId: 'livestock_farms', confidence: 'MED' }] },
  livestockFarmGoose: { status: 'verified', datasets: [{ datasetId: 'livestock_farms', confidence: 'MED' }] },
  livestockFarmSheep: { status: 'verified', datasets: [{ datasetId: 'livestock_farms', confidence: 'MED' }] },
  livestockFarmOther: { status: 'verified', datasets: [{ datasetId: 'livestock_farms', confidence: 'MED' }] },
  livestockSlaughter: { status: 'verified', datasets: [{ datasetId: 'slaughterhouses', confidence: 'HIGH' }] },
  livestockFeed: { status: 'verified', datasets: [{ datasetId: 'feed_factories', confidence: 'HIGH' }] },
  livestockMarket: { status: 'verified', datasets: [{ datasetId: 'livestock_markets', confidence: 'HIGH' }] },
  // 🏟️ 運動場館 Sports（全國 15,000 點，運動部 22849；catalog: sports/all_venues）
  sportsSchool: { status: 'verified', datasets: [{ datasetId: 'all_venues', confidence: 'HIGH' }] },
  sportsPublicOther: { status: 'verified', datasets: [{ datasetId: 'all_venues', confidence: 'HIGH' }] },
  sportsPrivate: { status: 'verified', datasets: [{ datasetId: 'all_venues', confidence: 'HIGH' }] },
  sportsPark: { status: 'verified', datasets: [{ datasetId: 'all_venues', confidence: 'HIGH' }] },
  sportsCenter: { status: 'verified', datasets: [{ datasetId: 'all_venues', confidence: 'HIGH' }] },
  agriculture: {
    status: 'verified',
    datasets: [{ datasetId: 'ftw_fields', confidence: 'MED' }],
  },
  agriLeisureFarmZones: {
    status: 'verified',
    datasets: [{ datasetId: 'leisure_farm_zones_2025', confidence: 'HIGH' }],
  },
  agriRuralRegen: {
    status: 'verified',
    datasets: [{ datasetId: 'rural_regen_communities_2025', confidence: 'HIGH' }],
  },
  ecoNetworkZones: {
    status: 'verified',
    datasets: [{ datasetId: 'eco_network_zones', confidence: 'HIGH' }],
  },
  agriSoil: {
    status: 'verified',
    datasets: [{ datasetId: 'soil_map_national', confidence: 'HIGH' }],
  },
  agriSoilFertility: {
    status: 'verified',
    datasets: [{ datasetId: 'soil_fertility_grid_250m', confidence: 'HIGH' }],
  },
  agriCropSuitability: {
    status: 'verified',
    datasets: [{ datasetId: 'crop_suitability_132', confidence: 'HIGH' }],
  },
  farmRoads: {
    status: 'verified',
    datasets: [{ datasetId: 'farm_roads', confidence: 'HIGH' }],
  },
  forestCompartments: {
    status: 'verified',
    datasets: [{ datasetId: 'national_forest_compartments', confidence: 'HIGH' }],
  },
  forestReserve: {
    status: 'verified',
    datasets: [{ datasetId: 'forest_reserve', confidence: 'HIGH' }],
  },
  forestRecreation: {
    status: 'verified',
    datasets: [{ datasetId: 'forest_recreation_areas', confidence: 'HIGH' }],
  },
  forestFlatParks: {
    status: 'verified',
    datasets: [{ datasetId: 'flat_forest_parks', confidence: 'HIGH' }],
  },
  forestTreatmentWorks: {
    status: 'verified',
    datasets: [{ datasetId: 'forestry_treatment_works', confidence: 'HIGH' }],
  },
  forestTrailSigns: {
    status: 'verified',
    datasets: [{ datasetId: 'mountain_trail_signs', confidence: 'HIGH' }],
  },
  forestSignalPoints: {
    status: 'verified',
    datasets: [{ datasetId: 'mountain_signal_points', confidence: 'HIGH' }],
  },
  forestEducationCenters: {
    status: 'verified',
    datasets: [{ datasetId: 'forest_education_centers', confidence: 'HIGH' }],
  },
  forestDamLakes: {
    status: 'verified',
    datasets: [{ datasetId: 'dam_lakes_in_forest', confidence: 'HIGH' }],
  },
  forestRoads: {
    status: 'verified',
    datasets: [{ datasetId: 'forest_roads', confidence: 'HIGH' }],
  },
  forestAlishanRail: {
    status: 'verified',
    datasets: [{ datasetId: 'wildlife_distribution_3rd_alt', confidence: 'HIGH' }],
  },
  hikingTrails: {
    status: 'verified',
    datasets: [{ datasetId: 'mountain_trail_signs', confidence: 'MED' }],
  },
  forestWildlife: {
    status: 'verified',
    datasets: [{ datasetId: 'wildlife_distribution_3rd', confidence: 'HIGH' }],
  },
  wasteTruck: {
    status: 'verified',
    datasets: [{ datasetId: 'garbage_collection', confidence: 'MED' }],
  },
  wasteSchedule: {
    status: 'verified',
    datasets: [{ datasetId: 'garbage_collection', confidence: 'MED' }],
  },
  wasteScheduleNote: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_collection_routes', confidence: 'LOW' }],
  },
  wasteCleaningSquads: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_cleaning_squads', confidence: 'MED' }],
  },
  wasteStopsStatic: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_collection_stops', confidence: 'HIGH' }],
  },
  wdClothes: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_positions_realtime', confidence: 'LOW' }],
  },
  wdMixed: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_positions_realtime', confidence: 'LOW' }],
  },
  wdRecyclingContainer: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_positions_realtime', confidence: 'LOW' }],
  },
  wdBattery: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_positions_realtime', confidence: 'LOW' }],
  },
  wfIncinerator: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_facilities', confidence: 'HIGH' }],
  },
  wfLandfill: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_facilities', confidence: 'HIGH' }],
  },
  wfLandfillCoastal: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_facilities', confidence: 'HIGH' }],
  },
  wfTransfer: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_facilities', confidence: 'HIGH' }],
  },
  wfMedical: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_facilities', confidence: 'HIGH' }],
  },
  wfMonitoring: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_facilities', confidence: 'MED' }],
  },
  wfRecycling: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_facilities', confidence: 'HIGH' }],
  },
  wfScrapYard: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_facilities', confidence: 'HIGH' }],
  },
  wfOther: {
    status: 'verified',
    datasets: [{ datasetId: 'waste_facilities', confidence: 'HIGH' }],
  },
  facPrimary: {
    status: 'verified',
    datasets: [{ datasetId: 'power_plants', confidence: 'MED' }],
  },
  facPlanned: {
    status: 'verified',
    datasets: [{ datasetId: 'power_plants', confidence: 'LOW' }],
  },
  facHistorical: {
    status: 'verified',
    datasets: [{ datasetId: 'power_plants', confidence: 'MED' }],
  },
  facSecondary: {
    status: 'verified',
    datasets: [{ datasetId: 'power_plants', confidence: 'MED' }],
  },
  facOsmSupplement: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_power', confidence: 'LOW' }],
  },
  powerGenerationUnit: {
    status: 'verified',
    datasets: [{ datasetId: 'power_generation', confidence: 'MED' }],
  },
  osmSubstationsEhv: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_power', confidence: 'HIGH' }],
  },
  osmSubstations: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_power', confidence: 'HIGH' }],
  },
  osmPowerLines: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_power', confidence: 'HIGH' }],
  },
  osmPowerTowers: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_power', confidence: 'HIGH' }],
  },
  powerPoles: {
    status: 'verified',
    datasets: [{ datasetId: 'power_poles', confidence: 'HIGH' }],
  },
  offshoreWindZones: {
    status: 'verified',
    datasets: [{ datasetId: 'offshore_wind_zones', confidence: 'HIGH' }],
  },
  osmWindTurbines: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_power', confidence: 'LOW' }],
  },
  windPlan: {
    status: 'verified',
    datasets: [{ datasetId: 'renewable', confidence: 'MED' }],
  },
  geothermalWells: {
    status: 'verified',
    datasets: [{ datasetId: 'geothermal_wells', confidence: 'HIGH' }],
  },
  renewablePermitsTaipei: {
    status: 'verified',
    datasets: [{ datasetId: 'renewable', confidence: 'HIGH' }],
  },
  evChargingStations: {
    status: 'verified',
    datasets: [{ datasetId: 'ev_charging_stations', confidence: 'HIGH' }],
  },
  gasStationCpc: {
    status: 'verified',
    datasets: [{ datasetId: 'gas_stations', confidence: 'MED' }],
  },
  gasStationFpcc: {
    status: 'verified',
    datasets: [{ datasetId: 'gas_stations', confidence: 'MED' }],
  },
  gasStationTaisugar: {
    status: 'verified',
    datasets: [{ datasetId: 'gas_stations', confidence: 'MED' }],
  },
  gasStationOther: {
    status: 'verified',
    datasets: [{ datasetId: 'gas_stations', confidence: 'MED' }],
  },
  gasStationCanonical: {
    status: 'verified',
    datasets: [{ datasetId: 'gas_stations', confidence: 'HIGH' }],
  },
  lpgSubpackaging: {
    status: 'verified',
    datasets: [{ datasetId: 'lpg_facilities_canonical', confidence: 'MED' }],
  },
  lpgRetailers: {
    status: 'verified',
    datasets: [{ datasetId: 'lpg_facilities_canonical', confidence: 'MED' }],
  },
  lngTerminal: {
    status: 'verified',
    datasets: [{ datasetId: 'gem_lng_terminals_tw', confidence: 'HIGH' }],
  },
  pipelineGas: {
    status: 'verified',
    datasets: [{ datasetId: 'gem_gas_pipelines_tw', confidence: 'HIGH' }],
  },
  pipelineOilGas: {
    status: 'verified',
    datasets: [{ datasetId: 'gem_oil_ngl_pipelines_tw', confidence: 'HIGH' }],
  },
  industrialRefinery: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_refineries', confidence: 'HIGH' }],
  },
  industrialStorageTank: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_storage_tanks_oil_gas', confidence: 'HIGH' }],
  },
  industrialPowerPlant: {
    status: 'verified',
    datasets: [{ datasetId: 'osm_fossil_power_plants', confidence: 'MED' }],
  },
  coalTerminal: {
    status: 'verified',
    datasets: [{ datasetId: 'gem_coal_terminals', confidence: 'HIGH' }],
  },
  fossilFuelInfra: {
    status: 'verified',
    datasets: [{ datasetId: 'gem_coal_plants', confidence: 'MED' }],
  },
  gasCoverageAll: {
    status: 'pulse_only',
    datasets: [],
    derivedFromLayers: ['gasStationCpc', 'gasStationFpcc', 'gasStationTaisugar', 'gasStationOther'],
    derivationType: 'coverage',
    processing: '全台加油站聚合 + OSRM 路網最近距離分析 → PMTiles（30km 覆蓋分級：0-5/5-10/10-20/20-30/30km+）',
    note: 'DERIVED: pulse-derived coverage analysis (PMTiles from gas stations + road netwo',
  },
  gasCoverageCpc: {
    status: 'verified',
    datasets: [{ datasetId: 'gas_stations', confidence: 'LOW' }],
  },
  gasCoverageFpcc: {
    status: 'verified',
    datasets: [{ datasetId: 'gas_stations', confidence: 'LOW' }],
  },
  gasCoverageTaisugar: {
    status: 'verified',
    datasets: [{ datasetId: 'gas_stations', confidence: 'LOW' }],
  },
  evIsland: {
    status: 'pulse_only',
    datasets: [],
    derivedFromLayers: ['evChargingStations'],
    derivationType: 'coverage',
    processing: '全台充電站 + 路網最近距離分析 → 反演孤島區域（縣市邊界內距任一充電站 > N km） PMTiles',
    note: 'DERIVED: pulse-derived island analysis (PMTiles from EV chargers + road network)',
  },
  submarineCables: {
    status: 'verified',
    datasets: [{ datasetId: 'submarine_cable', confidence: 'HIGH' }],
  },
  landingStations: {
    status: 'verified',
    datasets: [{ datasetId: 'submarine_cable', confidence: 'LOW' }],
  },
  schools: {
    status: 'verified',
    datasets: [{ datasetId: 'layer2_polygon', confidence: 'LOW' }],
  },
  convenienceStores: {
    status: 'verified',
    datasets: [{ datasetId: 'convenience_store', confidence: 'MED' }],
  },
  realEstateRentalGrid: {
    status: 'verified',
    datasets: [{ datasetId: 'real_estate', confidence: 'LOW' }],
  },
  realEstateRentalPoint: {
    status: 'verified',
    datasets: [{ datasetId: 'real_estate', confidence: 'HIGH' }],
  },
  realEstateSaleGrid: {
    status: 'verified',
    datasets: [{ datasetId: 'real_estate', confidence: 'LOW' }],
  },
  realEstateSalePoint: {
    status: 'verified',
    datasets: [{ datasetId: 'real_estate', confidence: 'HIGH' }],
  },
  realEstatePresaleGrid: {
    status: 'verified',
    datasets: [{ datasetId: 'real_estate', confidence: 'LOW' }],
  },
  realEstatePresalePoint: {
    status: 'verified',
    datasets: [{ datasetId: 'real_estate', confidence: 'HIGH' }],
  },
  satellitesTaiwan: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesYaogan: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesJilin: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesGaofen: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesTJS: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesBeidou: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesShiyan: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesUSA: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesJapan: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesRussia: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesIndia: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesKorea: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesFrance: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesGermany: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesItaly: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  satellitesIsrael: {
    status: 'verified',
    datasets: [{ datasetId: 'celestrak_satellites', confidence: 'HIGH' }],
  },
  newsEvents: {
    status: 'verified',
    datasets: [{ datasetId: 'layer2_polygon', confidence: 'LOW' }],
  },
  policeStation: {
    status: 'verified',
    datasets: [{ datasetId: 'police_stations', confidence: 'MED' }],
  },
  womenChildWarning: {
    status: 'verified',
    datasets: [{ datasetId: 'women_child_warning', confidence: 'MED' }],
  },
  speedCamera: {
    status: 'verified',
    datasets: [{ datasetId: 'speed_cameras', confidence: 'MED' }],
  },
  speedZoneSegment: {
    status: 'verified',
    datasets: [{ datasetId: 'speed_zone_segments', confidence: 'MED' }],
  },
  court: {
    status: 'verified',
    datasets: [{ datasetId: 'courts', confidence: 'HIGH' }],
  },
  prosecutorsOffice: {
    status: 'verified',
    datasets: [{ datasetId: 'prosecutors_offices', confidence: 'HIGH' }],
  },
  correctionalFacility: {
    status: 'verified',
    datasets: [{ datasetId: 'correctional_facilities', confidence: 'HIGH' }],
  },
  courtJurisdiction: {
    status: 'verified',
    datasets: [{ datasetId: 'court_jurisdictions', confidence: 'MED' }],
  },
  crimeAreaMonthly: {
    status: 'verified',
    datasets: [{ datasetId: 'crime_area_monthly', confidence: 'MED' }],
  },
  theftTaoyuan: {
    status: 'verified',
    datasets: [{ datasetId: 'theft_points_taoyuan', confidence: 'MED' }],
  },
  trafficAccidentYearly: {
    status: 'verified',
    datasets: [{ datasetId: 'traffic_accident_yearly', confidence: 'MED' }],
  },
  accidentTaipei: {
    status: 'verified',
    datasets: [{ datasetId: 'accident_taipei_dots', confidence: 'MED' }],
  },
  a1AccidentRealtime: {
    status: 'verified',
    datasets: [{ datasetId: 'traffic_accident', confidence: 'HIGH' }],
  },
  investigationBureau: {
    status: 'verified',
    datasets: [{ datasetId: 'investigation_bureau', confidence: 'MED' }],
  },
  antiCorruptionOffice: {
    status: 'verified',
    datasets: [{ datasetId: 'anti_corruption_offices', confidence: 'MED' }],
  },
  immigrationOffice: {
    status: 'verified',
    datasets: [{ datasetId: 'immigration_offices', confidence: 'HIGH' }],
  },
  coastGuardStation: {
    status: 'verified',
    datasets: [{ datasetId: 'coast_guard_stations', confidence: 'MED' }],
  },
  civilDefenseShelter: {
    status: 'verified',
    datasets: [{ datasetId: 'civil_defense_shelters', confidence: 'MED' }],
  },
  policeIsoSubstation: {
    status: 'verified',
    datasets: [{ datasetId: 'police_stations', confidence: 'LOW' }],
  },
  policeIsoPrecinct: {
    status: 'verified',
    datasets: [{ datasetId: 'police_stations', confidence: 'LOW' }],
  },
  policeIsoCityDept: {
    status: 'verified',
    datasets: [{ datasetId: 'police_stations', confidence: 'LOW' }],
  },
  // ── Stub entries for LayerVisibility keys not in THEMES (stale, unused, or pending wiring) ──
  medICUBeds: { status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' },
  wasteRoute: { status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' },
  wasteStop: { status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' },
  powerPlants: { status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' },
  powerPlantGlow: { status: 'pulse_only', datasets: [], note: '視覺實驗 layer，共用 get_ssot_power_plants_with_output SSOT' },
  substationEhvGlow: { status: 'pulse_only', datasets: [], note: '視覺實驗 layer，共用 get_osm_substations SSOT，filter EHV' },
  powerLinesGlow: { status: 'pulse_only', datasets: [], note: '視覺實驗 layer，共用 get_osm_power_lines SSOT，測試爆炸參數' },
  aviationRestrictedGlow: { status: 'pulse_only', datasets: [], note: '視覺實驗 layer，共用 aviation_airspace PMTiles rim glow 疊層' },
  powerStatusHud: { status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' },
  powerRegionDemand: { status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' },
  osmSolarFarms: { status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' },
  osmPowerPlantsStatic: { status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' },
  islandPowerGrid: { status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' },
  facOffshore: { status: 'pulse_only', datasets: [], note: 'not in active THEMES (stale/unused color)' },
  // 環境污染（來源 taipei-gis-analytics environment/pollution_source；PMTiles）
  pollutionFacility: {
    status: 'verified',
    datasets: [{ datasetId: 'pollution_source', confidence: 'HIGH' }],
    processing: 'EMS_S_01 列管對象 × EMS_P_46 裁處 → 介質×嚴重度 PMTiles（列管≠污染）',
  },
  pollutionPenaltyCritical: {
    status: 'verified',
    datasets: [{ datasetId: 'pollution_source', confidence: 'HIGH' }],
    processing: 'EMS_P_46 裁處事件 geocoded → severity_event=critical 重大裁處 PMTiles filter',
  },
  pollutionPenaltyGeneral: {
    status: 'verified',
    datasets: [{ datasetId: 'pollution_source', confidence: 'HIGH' }],
    processing: 'EMS_P_46 裁處事件 geocoded → severity_event=high/normal 一般裁處 PMTiles filter',
  },
  pollutionPenaltyMobile: {
    status: 'verified',
    datasets: [{ datasetId: 'pollution_source', confidence: 'HIGH' }],
    processing: 'EMS_P_46 裁處事件 geocoded → severity_event=mobile 移動污染 PMTiles filter',
  },
  pollutionSite: {
    status: 'verified',
    datasets: [{ datasetId: 'pollution_source', confidence: 'HIGH' }],
    processing: 'EMS_S_07 確認污染場址（S4）PMTiles',
  },
};

// ── Convenience helpers ──

export function getUpstreamFor(layerKey: keyof LayerVisibility): UpstreamRef {
  return UPSTREAM_REGISTRY[layerKey];
}

export function getAllVerifiedDatasets(): Set<string> {
  const out = new Set<string>();
  for (const ref of Object.values(UPSTREAM_REGISTRY)) {
    if (ref.status === 'verified') {
      for (const d of ref.datasets) out.add(d.datasetId);
    }
  }
  return out;
}

/** Resolve upstream catalog dataset_ids for any layer (verified or pulse_only).
 *  For pulse_only: transitively walk derivedFromLayers + include derivedFromDatasets.
 *  Cycle-safe via visited set. */
export function resolveUpstreamDatasets(
  layerKey: keyof LayerVisibility,
  visited: Set<string> = new Set()
): string[] {
  if (visited.has(layerKey)) return [];
  visited.add(layerKey);
  const ref = UPSTREAM_REGISTRY[layerKey];
  if (!ref) return [];
  const out = new Set<string>();
  for (const d of ref.datasets) out.add(d.datasetId);
  for (const d of ref.derivedFromDatasets ?? []) out.add(d);
  for (const l of ref.derivedFromLayers ?? []) {
    for (const d of resolveUpstreamDatasets(l as keyof LayerVisibility, visited)) out.add(d);
  }
  return [...out];
}
